-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.405516

-- 模块导入
-- .DFM.StandaloneLua.BusinessTool.HeroHelperTool
-- BDFM.Business.Module.BattlefieldEntryModule.BattlefieldEntryConfig
-- require

-- 常量定义
-- local AssetPathName
-- local AsyncShowUI
-- local BIG_MAP_GROUP_CONSTANT
-- local BattlePassServer
-- local BattlefieldEntry
-- local BattlefieldMapViewWindow
-- local BattlefieldModeSelector
-- local ButtonThumbnail
-- local ButtonThumbnailHD
-- local ChangeTDMMapGroup
-- local CheckHasValidHero
-- local CheckIsCommanderMode
-- local CheckIsCommanderUnlock
-- local CheckIsFlagBattleMode
-- local CheckIsMPMap
-- local CheckIsNightFightingMode
-- local CommonTips
-- local ConditionCurSeasonScore
-- local ConditionMPLevel
-- local ConditionPrevSeasonScore
-- local Config
-- local ConnectStrOr
-- local Desc
-- local EGameFlowStageType
-- local ELuaLogCategory
-- local Facade
-- local Field
-- local GameFlowManager
-- local GameMode
-- local GameModeServer

-- 函数实现
