-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.543187

-- 模块导入
-- IDFM.Business.Module.ActivityModule.UI.MagicTower.ActivityMagicTowerLogic
-- ODFM.Business.Module.ActivityModule.UI.MagicTower.ActivityMagicTowerCombatLogic
-- QDFM.Business.Module.ActivityModule.UI.MagicTower.ActivityMagicTowerConfigManager
-- RDFM.Business.Module.ActivityModule.UI.MagicTower.ActivityMagicTowerNumericalPanel
-- require

-- 常量定义
-- local Activity
-- local ActivityMagicTowerCombatPanel
-- local AddInputActionBinding
-- local AsyncSetImagePath
-- local AsyncShowUI
-- local BOSS
-- local Back
-- local BindBackAction
-- local CalculateRoundDamage
-- local Cancel
-- local CancelDelay
-- local CanvasPanel_0
-- local ClearTimerHandle
-- local CloseUI
-- local Collapsed
-- local CommonTips
-- local Config
-- local Confirm
-- local CreateCallBack
-- local Ctor
-- local DFCommonSpine
-- local DFCommonSpine_1
-- local DFImage_53
-- local DFTextBlock
-- local DFTextBlock_26
-- local DelayCall
-- local EDisplayInputActionPriority
-- local EInputEvent
-- local ELuaLogCategory
-- local EUMGSequencePlayMode

-- 函数实现
