-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:02.901275

-- 模块导入
-- GenLocalLogFuncELuaLogCategory	LuaMHerouiHeroAppearancePanelrequire/DFM.Business.Module.HeroModule.Logic.
--  DFM.YxFramework.Util.WidgetUtil
-- *DFM.Business.Module.HeroModule.HeroConfig
-- .DFM.StandaloneLua.BusinessTool.HeroHelperTool
-- .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- /DFM.Business.Module.HeroModule.Logic.HeroLogic
-- :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
-- :DFM.StandaloneLua.BusinessTool.LogAnalysis.ButtonIdConfig
-- ?DFM.Business.Module.IrisSafeHouseModule.Util.SafeHouseSyncUtil
-- ?DFM.Business.Module.LobbyDisplayModule.Logic.LobbyDisplayLogic
-- @DFM.Business.Module.LitePackageModule.Logic.LiteDownloadManager
-- MDFM.Business.Module.CommonUILibraryModule.UI.Library.DFCommonCheckButtonOnly
-- ODFM.Business.Module.CommonWidgetModule.UI.CommonCheckButton.CommonCheckDrawTab
-- import
-- require

-- 常量定义
-- local Add
-- local AddAxisInputActionBinding
-- local AddChild
-- local AddInputActionBinding
-- local AddLuaEvent
-- local AddNavWidgetToArray
-- local AddSubUI
-- local AfterScreenshotShare
-- local ApplyHeroScreenshot
-- local Assembled_CommonMessageTips_V2
-- local AsyncShowUI
-- local BP_SetMainTitle
-- local Back
-- local BackList
-- local BelongedHeroID
-- local BindCustomBoundaryNavRule
-- local BindCustomOnClicked
-- local BottomLeft
-- local BottomLeftIconText
-- local Bp_SetImage
-- local Bp_SetType
-- local BrandIcon
-- local BundleItems
-- local C002
-- local CanJumpTo
-- local CanvasPanel_0
-- local ClearSubUIByParent
-- local Click
-- local CloseUI
-- local Collapsed

-- 函数实现
