-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.462648

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMWeaponAssemblyuiActivityTaraMainrequire<DFM.Business.Module.ActivityModule.UI.Tara.Activ
--  DFM.YxFramework.Util.WidgetUtil
-- )DFM.Business.DataStruct.Common.Base.Deep
-- 7DFM.Business.Module.ActivityModule.Logic.ActivityLogic
-- :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
-- <DFM.Business.Module.ActivityModule.UI.Tara.ActivityTaraHead
-- =DFM.Business.Module.ActivityModule.UI.Tara.ActivityTaraItem1
-- =DFM.Business.Module.ActivityModule.UI.Tara.ActivityTaraItem2
-- >DFM.Business.Module.ActivityModule.UI.Tara.ActivityTaraPanel1
-- >DFM.Business.Module.ActivityModule.UI.Tara.ActivityTaraPanel2
-- import
-- require

-- 常量定义
-- local AAA
-- local AAB
-- local ActRewardAddTwo
-- local ActTara_Comment
-- local ActTara_Refresh
-- local ActTara_RuleDetails
-- local ActTara_Send
-- local ActTara_SwitchingCollections
-- local ActUITextBlock
-- local Activity
-- local ActivityMainPanel
-- local ActivityReceiveReward
-- local ActivityServer
-- local ActivityTaraMain
-- local ActivityTaraPop1
-- local Activity_Asara_Likes_It
-- local Add
-- local AddInputActionBinding
-- local AddLuaEvent
-- local AddNavWidgetToArray
-- local AllBloggers
-- local AllBlogsToRewards
-- local Anim
-- local Anim2
-- local Anim_pickup_in
-- local Anim_pickup_loop
-- local Assembled_CommonMessageTips_V5
-- local Assembled_CommonMessageTips_V8
-- local AsyncSetImagePath
-- local AsyncShowUI

-- 函数实现
