-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:02.790949

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMLitePackageUITable
UIName2IDLiteSelectDownloadPopUILayer	EUILayerPopLuaPath?DFM.Business.Module.LitePackageModule.UI.LiteSelectDownloadPopBPKeyWBP_WW_DownSelection_PopIsModalLiteSelectDownloadPopItemSubCDFM.Bus
-- <DFM.Business.Module.LitePackageModule.UI.LiteCommonDownload
-- =DFM.Business.Module.LitePackageModule.UI.LiteDownloadBtnHall
-- >DFM.Business.Module.LitePackageModule.UI.LitePackageMainPanel
-- ?DFM.Business.Module.LitePackageModule.UI.LiteSelectDownloadPop
-- @DFM.Business.Module.LitePackageModule.UI.LiteDownloadNormalItem
-- ADFM.Business.Module.LitePackageModule.UI.LitePackageDownloadItem
-- CDFM.Business.Module.LitePackageModule.UI.LiteSelectDownloadPopItem
-- HDFM.Business.Module.CommonUILibraryModule.UI.Library.DFCommonButtonOnly

-- 常量定义
-- local ALua_LitePackage_LitePackageMainPanel_Download_ALL_DOWNLOADED_TIP
-- local Anim
-- local BLua_LitePackage_LitePackageMainPanel_Download_DownloadResourceTip
-- local BLua_LitePackage_SystemSettingLitePackageCleanUpPanel_SelectedText
-- local BPKey
-- local BeforeLogin_Check_DLC
-- local BeforeLogin_Check_PreDownload
-- local BeforeLogin_Download_DLC
-- local BeforeLogin_Download_Failed
-- local BeforeLogin_Unzip_PreDownload
-- local CLua_LitePackage_LitePackageMainPanel_Download_WaitForHDDownloading
-- local CLua_LitePackage_SystemSettingLitePackageCleanUpPanel_DeleteComfirm
-- local Donwing
-- local Downloaded
-- local ELuaLogCategory
-- local ELua_LitePackage_SystemSettingLitePackageCleanUpPanel_NoDeletable_TIP
-- local EUILayer
-- local EVODownloadType
-- local FLua_LitePackage_LitePackageMainPanel_Download_DownloadHDCollectionTip
-- local FLua_LitePackage_LitePackageMainPanel_Download_DownloadingHDCollection
-- local Facade
-- local GLua_LitePackage_SystemSettingLitePackageCleanUpPanel_DeleteSuccess_TIP
-- local GenLocalLogFunc
-- local GetTable
-- local IsAnimBlock
-- local IsModal
-- local IsPoolEnable
-- local LITE_PAK_COMBINE_PROGRESS_TIP
-- local LITE_PAK_DOWNLOAD_MD5_ERROR
-- local LITE_PAK_FIX_DEEP_CHECK_MD5

-- 函数实现
