-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  evtCloudSettingSlotStateChanged
-- 2.  value not found in cloud data
-- 3. !DFM.YxFramework.Plugin.Json.Json
-- 4. !GetLocalCommonSettingDataAndHash
-- 5. ![CloudSettingLogicHD] DoSendMeta
-- 6. ![CloudSettingLogicHD] Send Meta:
-- 7. ![CloudSettingLogicHD] _SendStats
-- 8. "SystemSettingHDCloudSettingWindow
-- 9. "[CloudSettingLogicHD] Send Stats:
-- 10. "evtCloudSettingUploadStateChanged
-- 11. #[CloudSettingLogicHD] remoteStats 
-- 12. $GetCloudSettingAutoUploadJustClosed
-- 13. %d+
-- 14. &SystemSettingHDCloudSettingChangeName
-- 15. &[CloudSettingLogicHD] Fetched Setting
-- 16. &[CloudSettingLogicHD] remoteMetaData 
-- 17. &[CloudSettingLogicHD] skip Send Meta:
-- 18. '[CloudSettingLogicHD] Fetching Setting
-- 19. '[CloudSettingLogicHD] Send Meta Failed
-- 20. '[CloudSettingLogicHD] skip Send Stats:
-- 21. (A@
-- 22. (AA
-- 23. (AC
-- 24. (AD
-- 25. (BA
-- 26. (BD
-- 27. (DF
-- 28. ([CloudSettingLogicHD] Send Meta Succeed
-- 29. ([CloudSettingLogicHD] Send Stats Failed
-- 30. ([CloudSettingLogicHD] remoteKeySetting 
-- 31. (w@
-- 32. )@@
-- 33. )A@
-- 34. )AA
-- 35. )AB
-- 36. )AD
-- 37. )B@
-- 38. )BB
-- 39. )BC
-- 40. )BE
-- 41. )BH
-- 42. )C@
-- 43. )CG
-- 44. )DE
-- 45. )[CloudSettingLogicHD] Send Stats Succeed
-- 46. +[CloudSettingLogicHD] Fetch Setting Failed
-- 47. +[CloudSettingLogicHD] SendKeySetting data 
-- 48. ,@A
-- 49. ,[CloudSettingLogicHD] Fetch Setting Success
-- 50. ,[CloudSettingLogicHD] SendKeySetting index=

-- 重构的函数结构:

-- 可能的函数: !GetLocalCommonSettingDataAndHash
-- 可能的赋值: ,[CloudSettingLogicHD] SendKeySetting index=
-- 可能的赋值: /[CloudSettingLogicHD] SendCommonSetting index=
-- 可能的函数: /[CloudSettingLogicHD] _ApplyIndexForKeySetting
-- 可能的函数: 2[CloudSettingLogicHD] _ApplyIndexForCommonSetting
-- 可能的赋值: =[CloudSettingLogicHD] detect inconsistency set Setting empty
-- 可能的函数: CloudSettingLocalCommon
-- 可能的函数: CloudSettingLocalKeymapping
-- 可能的函数: CloudSettingLocalTimeStamp
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalSlotTimeStamp
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: IsLocal
-- 可能的函数: Local
-- 可能的函数: LocalNameDefault
-- 可能的函数: SetLocalSlotTimeStamp
-- 可能的函数: UpgradeForCloud
-- 可能的函数: UpgradeForCloudMeta
-- 可能的函数: _ApplyIndexForCommonSetting
-- 可能的函数: _ApplyIndexForKeySetting
-- 可能的函数: _GetKeyForCommonSetting
-- 可能的函数: _GetKeyForKeySetting
-- 可能的函数: _GetLocalCommonSettingData
-- 可能的函数: _GetLocalKey
-- 可能的函数: localIndex