-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  GetStandardMapNameByMatchModeId
-- 2. (AA
-- 3. (AD
-- 4. (w@
-- 5. )AA
-- 6. )AB
-- 7. )AC
-- 8. )AD
-- 9. )AE
-- 10. )BC
-- 11. ,@@
-- 12. ,@A
-- 13. ,@B
-- 14. /DFM.Business.Module.ChatModule.Logic.ChatLogic
-- 15. A@@
-- 16. AddListener
-- 17. AddListeners
-- 18. AddLuaEvent
-- 19. AddSingleCacheData
-- 20. AddTeamInviteMsg
-- 21. AgreeInviteByIndex
-- 22. Agreed
-- 23. ArenaGameRule
-- 24. AutoRejectRemainApply
-- 25. Chat
-- 26. ChatServer
-- 27. Clear
-- 28. Config
-- 29. ConvenientAgreeInvite
-- 30. ConvenientRejectInvite
-- 31. Ctor
-- 32. DEFAULT_APPOINT_COLD_TIME
-- 33. DirectRejectIfNeed
-- 34. EGameFlowStageType
-- 35. ELuaLogCategory
-- 36. EnterFlowType
-- 37. EnterameStage
-- 38. Events
-- 39. ExitGameStage
-- 40. Expired
-- 41. Game
-- 42. GameMode
-- 43. GameTeamInviteViewModel
-- 44. GenLocalLogFunc
-- 45. GetCacheData
-- 46. GetCurrentTime
-- 47. GetGameRuleNameByMatchModeId
-- 48. GetNoReceiveSignal
-- 49. GetPendingSum
-- 50. GetTDMModeNameByGroupId

-- 重构的函数结构:

-- 可能的函数: DirectRejectIfNeed
-- 可能的函数: GenLocalLogFunc