-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  DFM.YxFramework.Util.WidgetUtil
-- 2.  _AddSelfWidgetToNavWidgetByName
-- 3. !RecoverBottomBarInputSummaryList
-- 4. !SetBottomBarTempInputSummaryList
-- 5. !WBP_SetUpComponent_Perspective_1
-- 6. !WBP_SetUpComponent_Perspective_2
-- 7. "_AddSliderWidgetToNavWidgetByName
-- 8. $WBP_SetUpComponent_MultipleChoice_2
-- 9. (AA
-- 10. (B@
-- 11. (BA
-- 12. (w@
-- 13. )A@
-- 14. ,@@
-- 15. @DFM.Business.Module.SystemSettingModule.Logic.HD.SettingLogicHD
-- 16. A@@
-- 17. AddNavWidgetToArray
-- 18. BindBackHandler
-- 19. CheckUnsave
-- 20. Collapsed
-- 21. CommonBar
-- 22. CommonTips
-- 23. Config
-- 24. CreateCallBack
-- 25. Ctor
-- 26. DFMGamePlayerMode
-- 27. DescRootPanel
-- 28. EDFM.Business.Module.SystemSettingModule.Logic.HD.CloudSettingLogicHD
-- 29. EDFMGamePlayMode
-- 30. ELuaLogCategory
-- 31. ESystemSettingHDPanel
-- 32. FDFM.Business.Module.SystemSettingModule.Logic.HD.CommonSettingLogicHD
-- 33. Field
-- 34. GamePlayMode_SOL
-- 35. GenLocalLogFunc
-- 36. GetCurrentTabTypeHD
-- 37. GetGameState
-- 38. GetGlobalSummaryList
-- 39. GetWorld
-- 40. HDEntrance
-- 41. HDSetting
-- 42. Hittest
-- 43. IsBuildRegionCN
-- 44. IsInEditor
-- 45. Loc
-- 46. LocalNicknameDisplay
-- 47. LuaMSystemSetting
-- 48. LuaS
-- 49. MDFM.Business.Module.SystemSettingModule.UI.DFHD.SystemSettingHDLanguagePanel
-- 50. Module

-- 重构的函数结构:

-- 可能的函数: GenLocalLogFunc
-- 可能的函数: LocalNicknameDisplay
-- 可能的函数: _wtLocalNicknameDisplay