-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  SetCatchedMatchIdListAndGroupId
-- 2. !TransTimestamp2YYMMDDHHMMSSCNStr
-- 3. $BattlefieldPrepareLogic.InitMapInfo
-- 4. %evtBattlefieldEntryTeamMemberUpdated
-- 5. &CheckIsModeLockedByCommanderCondition
-- 6. (@A
-- 7. (AA
-- 8. (AB
-- 9. (BA
-- 10. (BE
-- 11. (BK
-- 12. (CA
-- 13. (CB
-- 14. (w@
-- 15. )@@
-- 16. )@A
-- 17. )@B
-- 18. )@C
-- 19. )@D
-- 20. )@E
-- 21. )AA
-- 22. )AD
-- 23. )B@
-- 24. )BB
-- 25. )BG
-- 26. )BattlefieldPrepareLogic.CheckIsMapEnough
-- 27. )CC
-- 28. )CG
-- 29. )[BattlefieldPrepareLogic] _OnEndMatching
-- 30. *[BattlefieldPrepareLogic]setpreparestate:
-- 31. +BattlefieldPrepareLogic.CheckMapIsDownload
-- 32. +BattlefieldPrepareLogic._OnNewSeasonComing
-- 33. +Could not start match with team currently.
-- 34. +[BattlefieldPrepareLogic] _OnStartMatching
-- 35. -[BattlefieldPrepare] View:_OnStartBtnClicked
-- 36. 0BattlefieldPrepareLogic:OnMatchGatePunishFailed
-- 37. 2BattlefieldPrepareLogic.CheckIsNeedDownloadAllMap
-- 38. 5BattlefieldPrepareLogic.CheckIsModeLockedByRankScore
-- 39. 7BattlefieldPrepareLogic.CheckIsModeLockedByPlayerLevel
-- 40. 7BattlefieldPrepareLogic:OnStartBtnClick, map not open!
-- 41. 8BattlefieldPrepareLogic:OnStartBtnClick, mode not open!
-- 42. ;BattlefieldPrepareLogic.CheckIsMapEnough map not enough!!!
-- 43. <DFM.Business.Module.IrisSafeHouseModule.IrisSafeHouseConfig
-- 44. >BattlefieldPrepareLogic.CheckIsModeLockedByCommanderCondition
-- 45. @DFM.Business.Module.LitePackageModule.Logic.LiteDownloadManager
-- 46. AccountPunishReason
-- 47. AccountServer
-- 48. AddListener
-- 49. ArmedForceServer
-- 50. BBattlefieldPrepareLogic.CheckMapIsDownload, modeList not valid!!!

-- 重构的函数结构:

-- 可能的函数: ArmedForceServer
-- 可能的函数: CheckWIFIDownloadQuests
-- 可能的函数: EArmedForceMode
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetCurArmedForceMode
-- 可能的函数: GetIsWaitForGotoGame
-- 可能的函数: H[BattlefieldPrepareLogic] GetIsWaitForGotoGame no need change startText
-- 可能的函数: Key2StrFormat
-- 可能的函数: SequentialFormat
-- 可能的函数: format
-- 可能的日志: logTDMMapBoardDesc