-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CallSceneCtrlFunctionBySubstage
-- 2.  DFM.YxFramework.Util.WidgetUtil
-- 3.  GetBuyLimitResetTimeByLimitType
-- 4.  PlayCharacterAnimSeqByFashionId
-- 5.  RecommendBundleItemIsPresentTip
-- 6.  RegStackUITopBarTabGroupRegInfo
-- 7.  _OnStoreBuyHotRecommendationSuc
-- 8.  evtStoreBuyHotRecommendationSuc
-- 9. !DisableDynamicNavConfigsbyWidget
-- 10. !GetBelongedHeroIdByHeroFashionId
-- 11. !GetDisplayPriceByProductItemData
-- 12. !RecoverBottomBarInputSummaryList
-- 13. !RegStackUITopBarCurrencyTypeList
-- 14. !SetDisplayWeaponAutoBoundAdapter
-- 15. "GetMallGiftIsBuyLimitedByShopData
-- 16. #AsyncOperateStreamLevelsBySubStage
-- 17. #InitResourceCommercializationTable
-- 18. #RecommendBundleAllItemBuyButtonTip
-- 19. #SetCharacterSuitAvatarWithSequence
-- 20. #_checkBuyBundlePriceAndReportEvent
-- 21. #evtStoreProductViewBundleItemClick
-- 22. $%d
-- 23. $DoSendStoreViewDetailEventReportLog
-- 24. $WeaponSkin/MeleeWeaponSkinDataTable
-- 25. %.0f
-- 26. &[ProductPreview] _OnRewardPanelClosed
-- 27. '[ProductPreview] OnPurchaseShippingNtf
-- 28. (A@
-- 29. (AA
-- 30. (AB
-- 31. (AC
-- 32. (AE
-- 33. (AJ
-- 34. (AW
-- 35. (CA
-- 36. (CS
-- 37. (DA
-- 38. ([ProductPreview] _ModuleDownloadResult 
-- 39. (_OnStoreProductViewBundleItemClickClick
-- 40. (w@
-- 41. )@@
-- 42. )@A
-- 43. )A@
-- 44. )AA
-- 45. )AB
-- 46. )AC
-- 47. )AD
-- 48. )AE
-- 49. )AF
-- 50. )AH

-- 重构的函数结构:

-- 可能的函数:  CallSceneCtrlFunctionBySubstage
-- 可能的函数: "GetMallGiftIsBuyLimitedByShopData
-- 可能的赋值: 7[ProductPreview] OnPurchaseShippingNtf, but res == nil
-- 可能的赋值: =DFM.StandaloneLua.BusinessTool.StructTool.WeaponAssemblyTool
-- 可能的赋值: C[ProductPreview] _OnStoreBuyHotRecommendationSuc isCashBuy == true
-- 可能的函数: DFMPlatformUtils
-- 可能的赋值: D[ProductPreview] _OnStoreBuyHotRecommendationSuc isCashBuy == false
-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetGetMallGiftRecordByGoodsId
-- 可能的函数: GetLocalRemainTime2Seconds
-- 可能的函数: GetNumberFormatStr
-- 可能的函数: GetSecondsFormatDDHHMMSS
-- 可能的函数: GetSecondsFormatDDHHMMSSString
-- 可能的函数: GetWeaponSkinIfOwned
-- 可能的函数: GiftName
-- 可能的函数: HidePlatformStoreUI
-- 可能的函数: PLATFORM_ANDROID
-- 可能的函数: PLATFORM_IOS
-- 可能的函数: SequentialFormat
-- 可能的函数: ShowPlatformStoreUI
-- 可能的函数: TopBarTitleGift
-- 可能的函数: _getIsGiftBuyLimited
-- 可能的函数: evtStoreBuyMallGiftSuc
-- 可能的函数: format
-- 可能的函数: isMallGift