-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  -> 
-- 2.  ActivityServer.evtSignResArrive
-- 3.  ActivityTypeMPComponentDelivery
-- 4.  ActivityTypeRecruitNewMilestone
-- 5.  AllActivityThemeEventTechConfig
-- 6.  CSActivityAhsarahTravelReplyReq
-- 7.  CSActivityAhsarahTravelTrackReq
-- 8.  CSActivityArchiveAudioFinishReq
-- 9.  CSActivityArknightsGameStartReq
-- 10.  CSActivityArknightsRefreshAdReq
-- 11.  CSActivityChangeExchangePlanReq
-- 12.  CSActivityMossReceiveMSAwardReq
-- 13.  GetReddotStateByTaskAndExchange
-- 14.  InitActivityThemeEventTechTable
-- 15.  InitBannerInfoRelatedByActivity
-- 16.  IsRoleSurveyInfoTaskStageRedDot
-- 17.  SendActivityExchangePasswordReq
-- 18.  SendActivitySOCSendRecvFlowsReq
-- 19.  SendActivityTaskReceiveAwardReq
-- 20.  evtActivityUnlockExchangeChange
-- 21.  evtFilingOnSequenceItemReceived
-- 22. !ActivityTypeSOLComponentDelivery
-- 23. !ActivityTypeSOLEquipmentDelivery
-- 24. !CSActivityArknightsChooseHeroReq
-- 25. !CSActivityOneClickRewardClaimReq
-- 26. !CSActivityStarFireChargeTowerReq
-- 27. !CSSettlementGetTdmMandelBrickReq
-- 28. !OnReloadLocalThemeEventTechTable
-- 29. !SendActivityReceiveFinalAwardReq
-- 30. !SendSelectFinalMilestoneAwardReq
-- 31. ![Magic_Tower] GameEndRes Failed!
-- 32. !ssy req exchange id and plan id 
-- 33. "ActivityTypeTestingWeaponTemplate
-- 34. "CSActivityChangeMilestoneAwardReq
-- 35. "CSActivityReceiveSequenceAwardReq
-- 36. "CSActivityRefreshDailyActivityReq
-- 37. "CSActivityRelinkReceiveMSAwardReq
-- 38. "CheckMilestoneFinalRewardFallback
-- 39. "FilterActivityInfosByModeLearning
-- 40. "GetActivityInfoByActivityIDAndTag
-- 41. "GetMilestoneFinalRewardChoiceInfo
-- 42. "OnReloadLocalNewbieChallengeTable
-- 43. "SendActivityTriggerReq_RoleSurvey
-- 44. "[Magic_Tower] GameEndRes Success!
-- 45. #ActivityServer.evtBannerBtnChanged
-- 46. #ActivityServer.evtBannerInfoUpdate
-- 47. #ActivityServer.evtMandelInfoUpdate
-- 48. #ActivityTypeRecruitGrowthMilestone
-- 49. #CSActivityCollectionSubmitPropsReq
-- 50. #CSActivityReceiveMilestoneAwardReq

-- 重构的函数结构:

-- 可能的函数:  InitBannerInfoRelatedByActivity
-- 可能的函数: !OnReloadLocalThemeEventTechTable
-- 可能的函数: "OnReloadLocalNewbieChallengeTable
-- 可能的函数: *--ActivityServer:OnReloadLocalTaskTable--
-- 可能的函数: +--ActivityServer:OnReloadLocalConstTable--
-- 可能的函数: ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- 可能的函数: .--ActivityServer:OnReloadLocalActivityTable--
-- 可能的函数: /--ActivityServer:OnReloadLocalTaskGoalsTable--
-- 可能的函数: /DFM.Business.DataStruct.Common.Base.Functional
-- 可能的函数: 4--ActivityServer:OnReloadLocalThemeEventTechTable--
-- 可能的函数: 5--ActivityServer:OnReloadLocalNewbieChallengeTable--
-- 可能的函数: CSStateBatchGetInfoReq
-- 可能的函数: ClearForecastTimers
-- 可能的函数: E[ActivityServer] InitBannerInfoRelatedByActivity Update! activityID:
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: HandleActivityLocalizeText
-- 可能的函数: HandleBannerLocalizeText
-- 可能的函数: HasForecastDataOnly
-- 可能的函数: InitLocalCustomTable
-- 可能的函数: IsLocalUser
-- 可能的函数: IsRoleSurveyExchangeInfoRedDot
-- 可能的函数: KEY_ErrorTipIfNeeded
-- 可能的函数: NumLocalUser
-- 可能的函数: OnForecastTimer
-- 可能的函数: OnReloadLocalActivityTable
-- 可能的函数: OnReloadLocalConstTable
-- 可能的函数: OnReloadLocalQuestionTable
-- 可能的函数: OnReloadLocalTaskGoalsTable
-- 可能的函数: OnReloadLocalTaskTable
-- 可能的函数: ProcessForecastTimers
-- 可能的赋值: T[ActivityServer] GetFilterBannerInfosByID BannerFilterInfosByID is nil or {}. ID = 
-- 可能的函数: Transform
-- 可能的函数: UpdateLocalActivityCurrency
-- 可能的函数: UpdateLocalCurrenNumByCycle
-- 可能的函数: _UpdateLocalCurrenNum
-- 可能的函数: _forecastTimers
-- 可能的函数: classify_config
-- 可能的函数: format