-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CallSceneCtrlFunctionBySubstage
-- 2.  DFM.YxFramework.Util.WidgetUtil
-- 3.  GetAccessoryIdBelongHeroFashion
-- 4.  GetHeroPropsMysticalLotteryData
-- 5.  PlayCharacterAnimSeqByFashionId
-- 6. !CreateHeroPropsItemWithCurScheme
-- 7. !DisableDynamicNavConfigsbyWidget
-- 8. !RecoverBottomBarInputSummaryList
-- 9. !_OnFashionVideoShowButtonClicked
-- 10. "GetHeroPropsMysticalClassSortName
-- 11. "IsFashionItemIdSelectedWithHeroId
-- 12. "_EnableHighLevelPanelGamepadInput
-- 13. %_OperateHeroCommercialByCurUseFahion
-- 14. (@@
-- 15. (A@
-- 16. (AA
-- 17. (AB
-- 18. (CA
-- 19. (DA
-- 20. (EA
-- 21. (w@
-- 22. )@@
-- 23. )A@
-- 24. )AA
-- 25. )AB
-- 26. )AC
-- 27. )AD
-- 28. )AG
-- 29. )AH
-- 30. )AY
-- 31. )B@
-- 32. )BB
-- 33. )BC
-- 34. )BF
-- 35. )BG
-- 36. )CD
-- 37. *DFM.Business.Module.HeroModule.HeroConfig
-- 38. *evtDownloadManagerNtfModuleDownloadResult
-- 39. ,@
-- 40. ,@@
-- 41. ,@E
-- 42. ,@F
-- 43. ,@G
-- 44. -[HeroEmotionUIBase]GoodsId error! GoodsId:%d
-- 45. -evtDownloadManagerNtfModuleStateMaybeChanged
-- 46. .DFM.StandaloneLua.BusinessTool.HeroHelperTool
-- 47. .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- 48. /DFM.Business.Module.HeroModule.Logic.HeroLogic
-- 49. :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
-- 50. :DFM.StandaloneLua.BusinessTool.LogAnalysis.ButtonIdConfig

-- 重构的函数结构:

-- 可能的函数:  CallSceneCtrlFunctionBySubstage
-- 可能的函数: FTextFormat
-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetMallGiftDataByGoodsID
-- 可能的函数: GetNumberFormatStr
-- 可能的函数: PlatformPaddingBox_6
-- 可能的函数: format
-- 可能的函数: wtPlatformPaddingBox_6