-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  AGPPlayerController::EndPlay_BS
-- 2.  BreakableItemBuildingStateArray
-- 3.  DFM.YxFramework.Util.WidgetUtil
-- 4.  EInputAction_VehicleFireBtnDown
-- 5.  OnJumpVaultClimbSplitModeChange
-- 6.  PhaseSelectTipHoverAnchorWidget
-- 7. !AEggQuestClientProxy::EndPlay_BS
-- 8. !BreakableItemOneSectionDataArray
-- 9. !OpenWorld.EnableFreezeRebasing 0
-- 10. !OpenWorld.EnableFreezeRebasing 1
-- 11. !OpenWorld.FixedWorldOriginType 0
-- 12. !OpenWorld.FixedWorldOriginType 2
-- 13. !UDFMWeaponDataComponentAmmo_Item
-- 14. "AAbilityWeaponThrowableFlashDrone
-- 15. "GetCurrentClientCharacterAvatarID
-- 16. "UBionicBirdHudView::TryForceGC_BS
-- 17. "UGPInputManager::OnInputKeyAim_BS
-- 18. #ABionicBirdActor::OnStopControl_ES
-- 19. #AEggQuestClientProxy::BeginPlay_ES
-- 20. #UGPRushMoveComponent::PlayAudio_BS
-- 21. #des.Anim.EnablePhysicsSimulation 0
-- 22. #des.Anim.EnablePhysicsSimulation 1
-- 23. $ABionicBirdActor::OnStartControl_ES
-- 24. $ADFMPlayerCameraManager::EndPlay_BS
-- 25. $AGameState_Breakthrough::EndPlay_ES
-- 26. $GPInputManager_OnInputKeyAim not HD
-- 27. $UGPInputManager::OnInputKeyUnAim_BS
-- 28. $georgecgong BB nil or driving false
-- 29. %DFM.YxFramework.Managers.Timer.Timer
-- 30. &GPInputManager_OnInputKeyUnAim not HD
-- 31. &MetaDorianDriver:Init() RTTITypeNum: 
-- 32. &MetaDorianDriver:Init() StubFuncNum: 
-- 33. &UGPInputManager::OnInputKeySideAim_BS
-- 34. &UQA_AbilityRushSetting::ApplyLogic_BS
-- 35. 'georgecgong OnVehicleWeaponSeat, go on
-- 36. (@@
-- 37. (A@
-- 38. (AA
-- 39. (AB
-- 40. (ABionicBirdActor::ProcessInputAction_BS
-- 41. (AC
-- 42. (AE
-- 43. (B@
-- 44. (BB
-- 45. (BC
-- 46. (EE
-- 47. (GPGameplay_UGPInputManager_BeginPlay_BS
-- 48. (GPInputManager_OnInputKeySideAim not HD
-- 49. (UGPInputManager::OnInputKeyUnSideAim_BS
-- 50. (UGPUserInterfaceUtil::IsThemeIDValid_BS

-- 重构的函数结构:

-- 可能的函数: "UBionicBirdHudView::TryForceGC_BS
-- 可能的函数: +AForestEggEntrance::OnPreloadOverlapEnd_ES
-- 可能的函数: ,DFMGameHud_UBionicBirdHudView_TryForceGC_BS
-- 可能的函数: 3DFMQuest_AForestEggEntrance_OnPreloadOverlapEnd_ES
-- 可能的赋值: 6GPInputManager_OnInputKeyAim IsMouseScrollBind Time= 
-- 可能的赋值: 8GPInputManager_OnInputKeyUnAim IsMouseScrollBind Time= 
-- 可能的赋值: :GPInputManager_OnInputKeySideAim IsMouseScrollBind Time= 
-- 可能的赋值: <GPInputManager_OnInputKeyUnSideAim IsMouseScrollBind Time= 
-- 可能的赋值: =ADFMPlayerCharacter_SetPlayerCameraManagerEncHandler_BS Next
-- 可能的赋值: =Breakthrough_UBattleFieldFreeBuildSkillMainView_OnHide_BS PC
-- 可能的赋值: =CarryBodyGlobalAction_InitCarryActorData_BS V2 Blackboard OK
-- 可能的赋值: =DFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS
-- 可能的赋值: =DFMGameHud_UDFMMobileWeaponTacticalEquipItem_OnBtnClicked_BS
-- 可能的赋值: =DFMGameplay_AAbilityWeaponThrowableFlashDrone_DoBeginPlay_BS
-- 可能的赋值: >GPGameplay_UWeaponDataComponentAmmo_OnWeaponAdd_ES == nullptr
-- 可能的赋值: @UDFMInputManager_ProcessLeanPeekAction IsMouseScrollBind Time= 
-- 可能的函数: AForestEggEntrance
-- 可能的函数: AddDorianFunction
-- 可能的函数: B[conezhou][DFMGameHud_UBionicBirdHudView_TryForceGC_BS]Null World
-- 可能的函数: B[conezhou][DFMGameHud_UBionicBirdHudView_TryForceGC_BS]TryForceGC
-- 可能的函数: E[conezhou][DFMGameHud_UBionicBirdHudView_TryForceGC_BS]TryForceGC_BS
-- 可能的函数: G[conezhou][DFMGameHud_UBionicBirdHudView_TryForceGC_BS]Skip TryForceGC
-- 可能的函数: GetLocalCharacter
-- 可能的函数: GetLocalGPPlayerController
-- 可能的函数: GetLocalPlayerCamp
-- 可能的函数: GetLocalRole
-- 可能的函数: GetTargetLocalCharacter
-- 可能的赋值: HDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS AnimIns = 
-- 可能的赋值: HDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS FPPMesh = 
-- 可能的函数: H[GPGameplay_AWeaponBase_OnRepWeaponEquipPosition_BS] Before, EquipPos: 
-- 可能的赋值: JDFMGameplay_APlayerExitBase_OnRep_EnteredCharacters_ES:ActorWrold == null
-- 可能的函数: MUDFInteractableCompProxy_FortificationProxy::IsCanInteract_Implementation_BS
-- 可能的函数: MUDFInteractableCompProxy_FortificationProxy::IsShowableTag_Implementation_BS
-- 可能的函数: M[conezhou][DFMGameHud_UBionicBirdHudView_TryForceGC_BS]Null WorldComposition
-- 可能的赋值: PDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS ActivateAnimIns = 
-- 可能的函数: PLATFORM_IOS
-- 可能的函数: RDFMGameplay_APlayerExitBase_OnRep_EnteredCharacters_ES:TargetLocalCharacter==null
-- 可能的函数: RDFMQuest_AForestEggEntrance_OnPreloadOverlapEnd_ES bClientHasLoadedReleventLevels
-- 可能的赋值: SDFMQuest_AEggQuestClientProxy_EndPlay_BS Leave Egg, bRebaseOriginIn3DSpace = false
-- 可能的函数: SDFMQuest_AForestEggEntrance_OnPreloadOverlapEnd_ES QALevelLoadHandleMeta isvalid()
-- 可能的函数: SetDorianFunction
-- 可能的函数: TDFMGameplay_APlayerExitBase_OnRep_EnteredCharacters_ES:TargetLocalCharacter != null
-- 可能的赋值: TDFMQuest_AEggQuestClientProxy_BeginPlay_ES Enter Egg, bRebaseOriginIn3DSpace = true
-- 可能的函数: TryForceGC
-- 可能的函数: TryStopLockLocalCharacter
-- 可能的函数: WDFMQuest_AForestEggEntrance_OnPreloadOverlapEnd_ES ClearTimer QALevelLoadTimeoutHandle
-- 可能的函数: YBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS
-- 可能的函数: YBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS
-- 可能的赋值: [DFMGameplay_UDFMWeaponDataComponentAmmo_Item_UpdateOptionSetting_BS WeaponOwner == nullptr
-- 可能的函数: \DFMQuest_AEggQuestClientProxy_EndPlay_BS Forest Leave Egg, OpenWorld.EnableFreezeRebasing 1
-- 可能的函数: ^DFMQuest_AEggQuestClientProxy_BeginPlay_ES Forest Enter Egg, OpenWorld.EnableFreezeRebasing 0
-- 可能的函数: `Breakthrough_AFreeBuildRankSkillPreviewPlacementActor_FindTargetPos_BS LocalCharacter isinvalid
-- 可能的赋值: bDFMGameplay_UDFMWeaponDataComponentAmmo_Item_UpdateOptionSetting_BS UClientBaseSetting == nullptr
-- 可能的赋值: cDFMGameplay_UDFMWeaponDataComponentAmmo_Item_UpdateOptionSetting_BS ClientGameSettingHD == nullptr
-- 可能的函数: fDFMQuest_AForestEggEntrance_OnPreloadOverlapEnd_ES Character has loaded levels, ReleasePlayerLocation
-- 可能的函数: iBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS World isinvalid
-- 可能的函数: iBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS World isinvalid
-- 可能的函数: kBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS SelfPtr isinvalid
-- 可能的函数: kBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS SelfPtr isinvalid
-- 可能的日志: logerror
-- 可能的日志: print
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS FreeBuildOwnerCamp==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS SelfPtr.RecycleTag==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS FreeBuildOwnerCamp==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS SelfPtr.RecycleTag==nil
-- 可能的函数: vBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS FortificationProxy isinvalid
-- 可能的函数: vBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS FortificationProxy isinvalid
-- 可能的函数: wBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS LocalCamp~=0 and LocalCamp~=1
-- 可能的函数: wBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS LocalCamp~=0 and LocalCamp~=1
-- 可能的函数: |Breakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS type(FreeBuildOwnerCamp) ~= number
-- 可能的函数: |Breakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS type(FreeBuildOwnerCamp) ~= number