-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CommonSlotView:_UpdateBgTexData
-- 2.  DFM.YxFramework.Util.WidgetUtil
-- 3.  GetItemView  self._fObtainCustomWarehouseIVFromPool is nil!!!
-- 4.  InitSplineAreaWidgetForSlotView
-- 5.  SetCustomWarehouseIVFromPool
-- 6.  _CalSlotItemLocationsFromCustom
-- 7. "_fObtainCustomWarehouseIVFromPool
-- 8. "_remainTryGetScrollBoxHeightTimes
-- 9. #CreateIVWarehouseTemplateBindOwner
-- 10. %CommonSlotView:OnSlotScroll_Internal
-- 11. &CheckItemViewPosAndSizeAlreadyCorrect
-- 12. 'CommonSlotView:SingleFrameTask_AddItem
-- 13. (@@
-- 14. (A@
-- 15. (BB
-- 16. (CJ
-- 17. (DefaultRemainTryGetScrollBoxHeightTimes
-- 18. (EF
-- 19. (EI
-- 20. (w@
-- 21. )@@
-- 22. )A@
-- 23. )AA
-- 24. )AE
-- 25. )BA
-- 26. )BD
-- 27. )CA
-- 28. )CB
-- 29. )DA
-- 30. )DF
-- 31. )DG
-- 32. )EA
-- 33. )EF
-- 34. )EG
-- 35. )EJ
-- 36. )EK
-- 37. )GN
-- 38. *]DispatchIVFrameTask add item to new task
-- 39. ,@
-- 40. ,@@
-- 41. ,@A
-- 42. .DFM.YxFramework.Managers.Coroutine.ObjectPool
-- 43. /]DispatchIVFrameTask remove item from old task
-- 44. 4DFM.Business.Module.InventoryModule.InventoryConfig
-- 45. 5]OnSlotScroll_Internal remove item from framing task
-- 46. 8DFM.StandaloneLua.BusinessTool.StructTool.ItemOperaTool
-- 47. :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
-- 48. =DFM.StandaloneLua.BusinessTool.StructTool.ItemSpaceAlgorithm
-- 49. A@@
-- 50. A@A

-- 重构的函数结构:

-- 可能的函数:  InitSplineAreaWidgetForSlotView
-- 可能的赋值: =DFM.StandaloneLua.BusinessTool.StructTool.ItemSpaceAlgorithm
-- 可能的赋值: CCommonSlotView:GetScrollBoxHeight succeed to get self._boxHeight =
-- 可能的赋值: ECommonSlotView:OnSlotScroll_Internal self:IsInRecycleMode() == false
-- 可能的函数: FORCE_USE_FRAMING
-- 可能的函数: ForceCalSlotItemLocation
-- 可能的函数: ForceRefreshThisFrame
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLastModifyReason
-- 可能的函数: LocalTObjectAllocerManager
-- 可能的函数: OnNotifyLuaResolutionResized
-- 可能的函数: PlayHighlightForItem
-- 可能的函数: TIMER_DURACTION_FOR_ONE_FLAME
-- 可能的赋值: VCommonSlotView:OnSlotScroll_Internal TryGetScrollBoxHeight because self._boxHeight<=0
-- 可能的赋值: \CommonSlotView:OnSlotScroll_Internal group=%d type=%d self._boxHeight changed from %f to %f
-- 可能的函数: _OnNotifyResolutionResized
-- 可能的函数: format
-- 可能的函数: iFA
-- 可能的函数: modifyTimeStamp