-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.   type is not correct
-- 2.  BindCarouselCacheItemCountEvent
-- 3.  Debug] 
-- 4.  not exists
-- 5. !CheckAbsolutePointInsideViewport
-- 6. !ESlateVisibility.HitTestSelfOnly
-- 7. !GetAbsolutePositionAtCoordinates
-- 8. !OnUserProcessItemsUpdateFinished
-- 9. "BindCarouselV2CacheItemCountEvent
-- 10. "ESlateVisibility.HitTestInvisible
-- 11. &----------------------boundingBoxA
-- 12. &----------------------boundingBoxB
-- 13. &ESlateVisibility.SelfHitTestInvisible
-- 14. (@@
-- 15. (A@
-- 16. (B@
-- 17. (CB
-- 18. (CC
-- 19. (CD
-- 20. (EE
-- 21. (FY
-- 22. (w@
-- 23. )A@
-- 24. )B@
-- 25. )BA
-- 26. )BB
-- 27. )BC
-- 28. )D@
-- 29. )DD
-- 30. )EF
-- 31. )FX
-- 32. -DFM.YxFramework.Managers.UI.Util.UIThemeUtil
-- 33. .*%.(.*)
-- 34. /targetIdx is out of range, correct to PageSize
-- 35. 1UIUtil.IsAOverlapByB(boundingBoxA, boundingBoxB)
-- 36. 2UIUtil.OnInputDeleteBtnClicked(wtEditableTextBox)
-- 37. 4UIUtil.RemoveScrollBoxClickStopScroll handle is nil
-- 38. 7current delegateName isnt matched with type 'userdata'
-- 39. :UIUtil.AddScrollBoxClickStopScroll scrollBoxWidget is nil
-- 40. :WndWaterfallScrollBox UISettings is nil, please check!!!!
-- 41. <UIUtil.AttachWidgetTo(...) alignWidget is nil, please check
-- 42. =UIUtil.AttachWidgetTo(...) adjustWidget is nil, please check
-- 43. A@A
-- 44. AA@
-- 45. AAA
-- 46. AAB
-- 47. ABB
-- 48. AboundingBoxA cant overlaped by boundingBoxB, it is bigger than b
-- 49. AbsoluteToLocal
-- 50. Add

-- 重构的函数结构:

-- 可能的赋值: =UIUtil.AttachWidgetTo(...) adjustWidget is nil, please check
-- 可能的函数: AbsoluteToLocal
-- 可能的函数: CheckIfAutoApplyTheme
-- 可能的函数: ForceLayoutPrepass
-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalSize
-- 可能的函数: GetMousePositionOnPlatform
-- 可能的赋值: L[ SWidgetCarouselPro ] ------------  targetIdx == nil, SetActivePage failed
-- 可能的函数: LocalToAbsolute
-- 可能的赋值: N[ SWidgetCarouselPro ] ------------  RenderSize is <= 0, SetActivePage failed
-- 可能的函数: OnBeforeCreateItem
-- 可能的赋值: T[ SWidgetCarouselPro ] ------------  carouselProWidget == nil, SetActivePage failed
-- 可能的赋值: V[ UDFExCommonCarouselProV2 ] ------------  targetIdx == nil, SetTargetPageOnce failed
-- 可能的赋值: ^[ UDFExCommonCarouselProV2 ] ------------  carouselProWidget == nil, SetTargetPageOnce failed
-- 可能的日志: logframe