-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  DFM.YxFramework.Util.MemoryUtil
-- 2.  DFM.YxFramework.Util.WidgetUtil
-- 3.  debug traceback: 
-- 4. !CommonVideoComponent:OnNavBack()
-- 5. !DisableDynamicNavConfigsbyWidget
-- 6. "CommonVideoFullScreenView:OnClose
-- 7. #CommonVideoFullScreenView:OnOpen()
-- 8. #CommonVideoFullScreenView:OnShow()
-- 9. #CommonVideoFullScreenView:_Reset()
-- 10. &CommonVideoFullScreenView:OnHideBegin
-- 11. &CommonVideoFullScreenView:OnShowBegin
-- 12. &CommonVideoFullScreenView:StopMedia()
-- 13. 'Cached Media Play End Callback Excute!
-- 14. 'CommonVideoFullScreenView:OnDeactivate
-- 15. 'CommonVideoFullScreenView:SetAutoClose
-- 16. (AA
-- 17. (BB
-- 18. (CB
-- 19. (w@
-- 20. )A@
-- 21. )AA
-- 22. )AB
-- 23. )AC
-- 24. )AD
-- 25. )CK
-- 26. )CommonVideoFullScreenView:HideSkipButton
-- 27. )CommonVideoFullScreenView:ShowSkipButton
-- 28. )DK
-- 29. )DT
-- 30. )DU
-- 31. *CommonVideoFullScreenView:HideProgressBar
-- 32. *CommonVideoFullScreenView:OnAnyKeyPressed
-- 33. *CommonVideoFullScreenView:OnInitExtraData
-- 34. *CommonVideoFullScreenView:SetHideSkipTime
-- 35. +CommonVideoFullScreenView:OnSkipBtnClicked
-- 36. ,@
-- 37. ,@A
-- 38. ,@B
-- 39. ,@F
-- 40. ,@H
-- 41. ,CommonVideoFullScreenView:OnCloseBtnClicked
-- 42. -CommonVideoFullScreenView:_OnMouseButtonDown
-- 43. /CommonVideoFullScreenView:OnGPInputTypeChanged
-- 44. 2CommonVideoFullScreenView:OnMediaPlayBegin() url:
-- 45. 2CommonVideoFullScreenView:PlayWithCommonMediaView
-- 46. 3[CommonVideoFullScreenView][OnMediaResDownloadEnd]
-- 47. 4CommonVideoFullScreenView:OnMediaPlayEnd() bIsSkip:
-- 48. 4CommonVideoFullScreenView:OnMediaResDownloadBegin()
-- 49. 5CommonVideoFullScreenView:AddGPInputTypeChangedEvent
-- 50. 5CommonVideoFullScreenView:OnInitExtraData RowName = 

-- 重构的函数结构:

-- 可能的赋值: 5CommonVideoFullScreenView:OnInitExtraData RowName = 
-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: format