-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  DFM.YxFramework.Util.WidgetUtil
-- 2. #_ResetTargetUI fail, targetWidget:
-- 3. (AB
-- 4. (w@
-- 5. )AB
-- 6. )AC
-- 7. )CD
-- 8. )CE
-- 9. )CL
-- 10. )DE
-- 11. +DFM.Business.Module.GuideModule.GuideLogic
-- 12. ,@@
-- 13. ,DFM.Business.Module.GuideModule.GuideConfig
-- 14. <dexzhou>: 
-- 15. A@@
-- 16. A@B
-- 17. A@C
-- 18. A@D
-- 19. ABC
-- 20. A_UpdateClickItemPosAndSize targetWidget has been destroyed, skip
-- 21. Add
-- 22. AddChild
-- 23. AddListener
-- 24. CanvasPanel_0
-- 25. CloseUI
-- 26. Collapsed
-- 27. Config
-- 28. CreateCPlusCallBack
-- 29. Ctor
-- 30. EGuideClickConfigOption
-- 31. EGuideEvent
-- 32. ELuaLogCategory
-- 33. ESlateVisibility
-- 34. FDFM.Business.Module.CommonBarModule.UI.BottomBarHD.InputSummaryItemHD
-- 35. FVector2D
-- 36. Facade
-- 37. Field
-- 38. GPInputDelegates
-- 39. GPInputHelper
-- 40. GenLocalLogFunc
-- 41. Get
-- 42. GetCachedGeometry
-- 43. GetCurrentInputType
-- 44. GetGameInstance
-- 45. GetGlobalPosAndSizeByWidget
-- 46. GetLocalPosAndSize
-- 47. GetParent
-- 48. GetRealClickTipsText
-- 49. GetZorder
-- 50. Guide

-- 重构的函数结构:

-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalPosAndSize
-- 可能的函数: _localPos
-- 可能的函数: _localSize
-- 可能的函数: uiForCalSizeAndPosData