-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  Debug ]------------- [
-- 2.  GF
-- 3.  SubStage TryUnloadLinkSubStage
-- 4.  SubStageName:
-- 5.  TryPostLoadLinkedSubStage_PopUI
-- 6.  TryUnloadAllLinkSubStage
-- 7.  to:
-- 8. !OnLinkSubStageLoadFinishCallback
-- 9. "TryPostLoadLinkedSubStage_StackUI
-- 10. #AsyncOperateStreamLevelsBySubStage
-- 11. #CheckIsStreamLevelLoadedBySubStage
-- 12. #TryBatchLoadLinkSubStageByUIIdList
-- 13. (A@
-- 14. (B@
-- 15. (w@
-- 16. )AB
-- 17. )BA
-- 18. )BB
-- 19. )BF
-- 20. )CD
-- 21. )CE
-- 22. ,@@
-- 23. ,@A
-- 24. -DFM.YxFramework.Managers.UI.Util.UIDebugUtil
-- 25. .DFM.YxFramework.Managers.UI.Util.UIConfigUtil
-- 26. 3DFM.YxFramework.Managers.UI.Platform.PlatformLogic
-- 27. =[ UI LinkSubStage ]------------- Link curStackUINavId is nil
-- 28. @[ UI LinkSubStage ]-------------[Pop] Link curPopUINavId is nil
-- 29. AssetLoading
-- 30. BPKey
-- 31. BackToLastSubStage
-- 32. CancelDelay
-- 33. CommitTransition
-- 34. CreateCallBack
-- 35. Ctor
-- 36. DelayCall
-- 37. Destroy
-- 38. ELayerRuleChangeReason
-- 39. ELevelPriority
-- 40. ELuaLogCategory
-- 41. ESubStage
-- 42. ETransitionChangeReason
-- 43. EUILayer
-- 44. EnterSubStage
-- 45. Events
-- 46. Facade
-- 47. GameFlowManager
-- 48. GenLocalLogFunc
-- 49. GetCurrentStackUI
-- 50. GetCurrentStackUIId

-- 重构的函数结构:

-- 可能的函数: 3DFM.YxFramework.Managers.UI.Platform.PlatformLogic
-- 可能的赋值: =[ UI LinkSubStage ]------------- Link curStackUINavId is nil
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: IsForceAreaType
-- 可能的赋值: a[ UI LinkSubStage ]------------- BatchUIHandle next(mapSubStageNeedLoad) == nil
-- 可能的日志: logframe
-- 可能的赋值: toSubStage == curStage ** from: