-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  GetTDMSettlementTeamHeroFashion
-- 2.  GetTeammateUsedLifeFromPlayerId
-- 3.  HighlightMomentMPSettlementInfo
-- 4.  SetHighlightMomentSettlemtnInfo
-- 5.  SettlementServer:GetEndGameInfo
-- 6.  SettlementServer:GetEndGameType
-- 7.  SettlementServer:GetHitDistance
-- 8.  SettlementServer:GetKillerLevel
-- 9.  SettlementServer:GetRaidKillNum
-- 10.  _SortRaidSettlementTeamInfoList
-- 11.  evtOnReqForSettlementInfoFailed
-- 12.  evtStartCameraMovementBroadCast
-- 13.  kGspPlayerDeathReasonKilledByAI
-- 14.  kGspPlayerGameStatusTypeEndGame
-- 15.  now == 
-- 16.  res.mode:
-- 17. !DFM.YxFramework.Plugin.Json.Json
-- 18. !F 
-- 19. !F!
-- 20. !F"
-- 21. !F#
-- 22. !F$
-- 23. !F%
-- 24. !F&
-- 25. !F'
-- 26. !GetSOLEliminationReplayStartTime
-- 27. !GetTDMSettlementMVPTeamEquipInfo
-- 28. !GetTDMSettlementWeaponChangeFlag
-- 29. !HighlightMomentSOLSettlementInfo
-- 30. !SetSOLEliminationReplayStartTime
-- 31. !SettlementServer:GetAccidentType
-- 32. !SettlementServer:GetQuitGameInfo
-- 33. !SettlementServer:GetRaidLevelId_
-- 34. !SettlementServer:GetRaidUsedLife
-- 35. !_ResetRaidSettlementTeamInfoList
-- 36. !kGspPlayerGameStatusTypeQuitGame
-- 37. "CSPlayerInfoCommanderBePraisedNtf
-- 38. "GetRaidTeamCarryInPropsPriceCount
-- 39. "OnPlayerInfoCommanderBePraisedNtf
-- 40. "SetHighlightMomentMPSettlemtnInfo
-- 41. "SettlementServer:GetCarryOutProps
-- 42. "SettlementServer:GetFatalBodyPart
-- 43. "SettlementServer:GetMatchInfoType
-- 44. "SettlementServer:GetTeammateArray
-- 45. "kGspPlayerDeathReasonKilledByBoss
-- 46. #GetArenaTeamPlayerInfoListByTeamID
-- 47. #GetTDMSettlementMVPTeamHeroFashion
-- 48. #GetTDMSettlementPlayerInfoNameById
-- 49. #SettlementServer:GetKillerWeaponId
-- 50. #SettlementServer:GetMatchInfoMapId

-- 重构的函数结构:

-- 可能的函数:  GetTeammateUsedLifeFromPlayerId
-- 可能的函数:  evtOnReqForSettlementInfoFailed
-- 可能的赋值:  now == 
-- 可能的函数: !SettlementServer:GetRaidUsedLife
-- 可能的函数: $CSSettlementGetNewSettlementInfoReq
-- 可能的函数: )SettlementServer:ReqForSOLSettlementInfo
-- 可能的函数: )SettlementServer:ReqForTDMSettlementInfo
-- 可能的函数: *SettlementServer:ReqForRaidSettlementInfo
-- 可能的函数: 6SettlementModule:OnReceiveSettlementNtf tdm force gc 
-- 可能的函数: <SettlementModule:ReqForTDMSettlementInfo now in game 2 show
-- 可能的赋值: <SettlementServer:ExceptionSettlementReq error res.result ==
-- 可能的赋值: <SettlementServer:OnReceiveSettlementNtf error res.result ==
-- 可能的赋值: =SettlementServer:ExceptionSettlementReq Mp has_match is true
-- 可能的赋值: =SettlementServer:GetTDMSettlementMVPTeamHeroFashion MVPteam 
-- 可能的赋值: =SettlementServer:GetTDMSettlementTeamInfo HeroidList is nil!
-- 可能的赋值: =SettlementServer:IsMpSettlementRankShield, rank_shields num:
-- 可能的函数: =SettlementServer:ReqForSOLSettlementInfo error res.result ==
-- 可能的函数: =SettlementServer:ReqForTDMSettlementInfo error res.result ==
-- 可能的函数: >SettlementServer:ReqForRaidSettlementInfo error res.result ==
-- 可能的函数: ?SettlementServer:ReqForTDMSettlementInfo error curGameFlow is 
-- 可能的赋值: ASettlementServer:OnReceivePlayerBanNtf ignore because reason = 2
-- 可能的函数: CSGetArenaSettlementInfoReq
-- 可能的函数: CSGetRaidSettlementInfoReq
-- 可能的函数: CSGetTDMSettlementInfoReq
-- 可能的函数: CloseForceQuit
-- 可能的函数: DFMPlatformActivityManager
-- 可能的函数: Difficulty
-- 可能的函数: DifficultyDesc
-- 可能的函数: FOnReqForSettlementInfoFailed
-- 可能的函数: ForceGC
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetPlayerPlatformIdByOpenId
-- 可能的函数: GetRaidMapNameAndDifficulty
-- 可能的函数: GetRaidUsedLife
-- 可能的函数: HandleLeaveMatchForPS5Activity
-- 可能的函数: NSettlementServer:ReqForSOLSettlementInfo ignore res because CurrentGameFlow =
-- 可能的函数: OnLeaveMatchForActivity
-- 可能的函数: PlatformMatchInfo
-- 可能的函数: PlatformMemberInfo
-- 可能的函数: ReqForArenaSettlementInfo
-- 可能的函数: ReqForRaidSettlementInfo
-- 可能的函数: ReqForSOLSettlementInfo
-- 可能的函数: ReqForTDMSettlementInfo
-- 可能的赋值: VSettlementServer:OnReceiveSettlementNtf self.bGetNtf=false because currentGameFlow is
-- 可能的赋值: YSettlementServer:OnReceiveSettlementNtf roomid not equality , dont req settPkg! this == 
-- 可能的函数: ZSettlementServer:ReqForTDMSettlementInfo roomid not equality , dont req settPkg! this == 
-- 可能的函数: _SetRaidMapNameAndDifficulty
-- 可能的函数: _raidMapDifficulty
-- 可能的函数: difficulty
-- 可能的函数: format
-- 可能的函数: passed_life