-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  ClearPanelHandlesGreatThanLevel
-- 2.  DurabilityReductionRepairInGame
-- 3.  GetRepairEfficTextByHelmetLevel
-- 4.  GetShopBuyPriceRichTextByItemV2
-- 5.  ItemDetailLogic.PreCreateSolUIs
-- 6.  JumpToMysticalSkinSellPopWindow
-- 7.  OnPutInCollectionItemBtnClicked
-- 8.  ReturnItemDetailSubDetailHandle
-- 9.  item 
-- 10.  nil 
-- 11. !GetAbsolutePositionAtCoordinates
-- 12. !GetSItemDetailStructByExchangeId
-- 13. !OnTryOpenItemDetailPanel widget:
-- 14. !OnUnLoadCollectionItemBtnClicked
-- 15. !RemoveWorkshopItemFromTargetPool
-- 16. !TransTimestamp2YYMMDDHHMMSSCNStr
-- 17. !itemDetail source map cfg is nil
-- 18. !ruochen: no map for selected key
-- 19. "CloseAllItemDetailSubDetailHandle
-- 20. "ECurrencyClientType2RichIconTxtV2
-- 21. "GetWorldEntranceInfoByMapIDPrefix
-- 22. "please check WeaponSkinDataTable:
-- 23. #CloseAllCacheItemDetailPanelHandle
-- 24. #ItemOperateActionMethod_SimpleList
-- 25. #K!
-- 26. $#allSourceInfo > 0, itemStruct.id: 
-- 27. $OnInteractionPanelVisibilityChanged
-- 28. $WeaponSkin/MeleeWeaponSkinDataTable
-- 29. %LevelUpExtItemFail_MaterialNotEnough
-- 30. %OnInteractionPanelVisibilityChanged:
-- 31. %SetOnCloseSimpleBtnListPanelCallback
-- 32. %not keyMapInfoConfig! keyLevelName: 
-- 33. %ruochen can't find mapinfo component
-- 34. %s %s
-- 35. &#allUsePlaceInfo > 0, itemStruct.id: 
-- 36. 'CloseAllItemDetailSubDetailPanelHandle
-- 37. 'GetWeaponpFunctionTableRowByFunctionId
-- 38. 'ItemDetailLogic.OnAssemblyBtnClicked: 
-- 39. 'ItemDetailLogic.PreCreateSolUIs finish
-- 40. '[ItemDetailTips] No Tips Cfg, Tips Id:
-- 41. (@A
-- 42. (A@
-- 43. (AA
-- 44. (AC
-- 45. (AD
-- 46. (AE
-- 47. (BA
-- 48. (BB
-- 49. (CB
-- 50. (DA

-- 重构的函数结构:

-- 可能的函数: !ruochen: no map for selected key
-- 可能的函数: 'GetWeaponpFunctionTableRowByFunctionId
-- 可能的赋值: )<customstyle color="Color_DarkNegative">
-- 可能的函数: ,ruochen: no door datatable for selected key
-- 可能的赋值: =DFM.StandaloneLua.BusinessTool.StructTool.WeaponAssemblyTool
-- 可能的函数: ArmedForce
-- 可能的函数: ArmedForceServer
-- 可能的函数: CloseItemDetailForLootPanel
-- 可能的函数: EArmedForceMode
-- 可能的函数: FUNCTION
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetAmmoListForWeapon
-- 可能的函数: GetBodyArmorFunctionById
-- 可能的函数: GetCurArmedForceMode
-- 可能的函数: GetFunctionParamByAdapterId
-- 可能的函数: GetHelmetArmorFunctionById
-- 可能的函数: GetItemArmedForceCfgNew
-- 可能的函数: GetNumberFormatStr
-- 可能的函数: GetPartsFunctionDataTable
-- 可能的函数: GetWeaponFunctionID2RulesIDTab
-- 可能的函数: GetWeaponFunctionIdByItemId
-- 可能的函数: HPDifferenceParam
-- 可能的函数: HelmetHPDifferenceParam
-- 可能的函数: IsArmedForceUniquePropByItem
-- 可能的函数: IsRandomGift
-- 可能的函数: Key2StrFormat
-- 可能的函数: Modify
-- 可能的函数: NotifyAsyncTaskDone
-- 可能的函数: RecFunctionTableManager
-- 可能的函数: SequentialFormat
-- 可能的函数: TryFindLocationForItem
-- 可能的函数: UseGift
-- 可能的函数: VerifyItemForTargetSlot
-- 可能的函数: format