-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CustomVerticalSensitivityFactor
-- 2.  GyroFireCustomSensitivityFactor
-- 3.  RotationSensitivityArray_Custom
-- 4. !DFM.YxFramework.Plugin.Json.Json
-- 5. !FireSpeedAccelerationSensitivity
-- 6. !GetCurrentCustomSensitivityArray
-- 7. !GetSavedForMiniWorldDisplayStyle
-- 8. !GyroFireCustomZoomratedMDVFactor
-- 9. !GyroFireRotationSensitivityArray
-- 10. !Process_SenslibilityValueChanged
-- 11. !SetSavedForMiniWorldDisplayStyle
-- 12. !SystemSettingModule:OnInitModule
-- 13. !_OnMobilePostGameHUDStateChanged
-- 14. "ApplyRecommandGraphicsSettingMisc
-- 15. "CheckAndShowResizableBarWarningHD
-- 16. "CustomHorizontalSensitivityFactor
-- 17. "GyroFireRotationSensitivityArray0
-- 18. "GyroFireRotationSensitivityArray1
-- 19. "_OnPostGameHUDStateChangedHandler
-- 20. #GetCurrentCustomDefaultSensitivity
-- 21. #RemoveAllJsonProtoListenerByCaller
-- 22. #SystemSettingHDPersonalInformation
-- 23. #_BindSystemSettingHDEntranceAction
-- 24. $ApplyRecommandGraphicsQulitySetting
-- 25. $ApplyRecommandGraphicsSettingMiscHD
-- 26. $FireCustomVerticalSensitivityFactor
-- 27. $QuickSPCustomPrecisionShootingRifle
-- 28. $RemoveDisplayActoinBingingForHandle
-- 29. %GetCurrentGyroCustomSensitivityArray
-- 30. %Process_GroySenslibilityValueChanged
-- 31. %RotationSpeedAccelerationSensitivity
-- 32. %_UnbindSystemSettingHDEntranceAction
-- 33. %s,%s
-- 34. &ApplyRecommandGraphicsQulitySettingHD
-- 35. &FireCustomHorizontalSensitivityFactor
-- 36. 'GetCurrentGyroCustomDefaultSensitivity
-- 37. 'SystemSettingModule:SendAnalysisData()
-- 38. (A@
-- 39. (AA
-- 40. (AC
-- 41. (BA
-- 42. (CA
-- 43. (FA
-- 44. (GyroFireCustomVerticalSensitivityFactor
-- 45. (w@
-- 46. )A@
-- 47. )AA
-- 48. )AB
-- 49. )AC
-- 50. )AD

-- 重构的函数结构:

-- 可能的函数: !GetSavedForMiniWorldDisplayStyle
-- 可能的函数: !SetSavedForMiniWorldDisplayStyle
-- 可能的函数: #SystemSettingHDPersonalInformation
-- 可能的函数: $QuickSPCustomPrecisionShootingRifle
-- 可能的函数: $RemoveDisplayActoinBingingForHandle
-- 可能的函数: ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- 可能的赋值: 1SystemSettingModule:_OnGetLogUploadResult = true
-- 可能的赋值: 2SystemSettingModule:_OnGetLogUploadResult = false
-- 可能的函数: ArmedForceServer
-- 可能的函数: EArmedForceMode
-- 可能的赋值: FSystemSettingModule:OnOrthoProjectionStateChanged  PS5 Pro isOrtho = 
-- 可能的函数: FunctionBtnRotationMode
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetCurArmedForceMode
-- 可能的函数: PLATFORM_GEN9
-- 可能的函数: PrecisionShootingRifle
-- 可能的函数: QuickSPCustomRifle
-- 可能的函数: QuickScope_PrecisionRifle
-- 可能的函数: QuickScope_PrecisionRifle_MP
-- 可能的函数: QuickScope_Rifle
-- 可能的函数: QuickScope_Rifle_MP
-- 可能的函数: Rifle
-- 可能的函数: bIsAimMagnify
-- 可能的函数: format
-- 可能的日志: print