-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  gameFlowType:
-- 2.  worldName delay:
-- 3.  worldName:
-- 4. "DFM.YxFramework.Util.AnalysisUtil
-- 5. #[ GFChange VS WorldCleanUp ]------------------------ self.stubLoadingUIRes:ClearAllResRefs 
-- 6. %DFM.YxFramework.Managers.ManagerBase
-- 7. &[UIManager] EnableLifeFunctionFraming
-- 8. (A@
-- 9. (AA
-- 10. (BA
-- 11. (BE
-- 12. (DFM.YxFramework.Managers.UI.Util.UIUtil
-- 13. (w@
-- 14. )AE
-- 15. )AF
-- 16. )AI
-- 17. *DFM.YxFramework.Managers.UI.LuaUIBaseView
-- 18. *DFM.YxFramework.Managers.UI.UIGlobalConst
-- 19. , UINavId == 
-- 20. , is not a preloaded sub view, 
-- 21. ,@@
-- 22. ,@A
-- 23. ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- 24. /DFM.YxFramework.Managers.Resource.Stub.ResStub
-- 25. /DFM.YxFramework.Managers.UI.Input.InputMonitor
-- 26. /DFM.YxFramework.Managers.UI.Util.UIReleaseUtil
-- 27. 1DFM.YxFramework.Managers.UI.Handle.BatchUIHandle
-- 28. 1DFM.YxFramework.Managers.UI.Util.UISimulatorUtil
-- 29. 2DFM.YxFramework.Managers.UI.Handle.SingleUIHandle
-- 30. 3DFM.YxFramework.Managers.Resource.Util.ResPathUtil
-- 31. 4DFM.YxFramework.Managers.UI.Part.UIManager_InsLogic
-- 32. 4DFM.YxFramework.Managers.UI.Part.UIManager_ResLogic
-- 33. 5DFM.YxFramework.Managers.UI.Part.UIManager_LinkLogic
-- 34. 5DFM.YxFramework.Managers.UI.Part.UIManager_RuleLogic
-- 35. 6CreateSubUI failed, uiSettings 
-- 36. 6DFM.YxFramework.Managers.UI.Part.UIManager_LayerLogic
-- 37. 6DFM.YxFramework.Managers.UI.Part.UIManager_ThemeLogic
-- 38. 7DFM.YxFramework.Managers.UI.Part.UIManager_UECallLogic
-- 39. 8DFM.YxFramework.Managers.UI.Part.UIManager_SubPackLogic
-- 40. 9DFM.YxFramework.Managers.UI.Input.Debug.InputDebugHelper
-- 41. ;DFM.YxFramework.Managers.UI.Part.UIManager_AliveCountLogic
-- 42. ;DFM.YxFramework.Managers.UI.Part.UIManager_NavigationLogic
-- 43. A@@
-- 44. A@A
-- 45. A@B
-- 46. A@D
-- 47. AA@
-- 48. Add
-- 49. AddListener
-- 50. AddSubUI

-- 重构的函数结构:

-- 可能的函数: &[UIManager] EnableLifeFunctionFraming
-- 可能的赋值: , UINavId == 
-- 可能的函数: ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- 可能的函数: CacheUIForCurrentFrame
-- 可能的赋值: DCreateSubUI failed, uiSettings.UILayer ~= EUILayer.Sub, UINavId == 
-- 可能的函数: DFMLocalizationManager
-- 可能的函数: EnableLifeFunctionFraming
-- 可能的函数: EnablePerformanceMode
-- 可能的函数: ForceCheckPendingUIParents
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: OnForceCleanUpUI
-- 可能的函数: OnLoadingBeforeChange
-- 可能的函数: TIMER_DURACTION_FOR_ONE_FLAME
-- 可能的函数: cacheUIForCurrentFrame
-- 可能的函数: evtPopUIBeforeChange
-- 可能的函数: evtStackUIBeforeChange
-- 可能的函数: evtStackUIBeforeChangePhase2
-- 可能的函数: gEnableLifeFunctionFraming
-- 可能的日志: logbox
-- 可能的日志: logframe