-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  BattlefieldEntryField:_SaveMaps
-- 2.  SetCatchedMatchIdListAndGroupId
-- 3.  evtBattlefieldEntryModesChanged
-- 4. $BattlefieldEntryField:_OnMapChanged
-- 5. %BattlefieldEntryField:GetHasResetMap
-- 6. %BattlefieldEntryField:GetMatchTipsHD
-- 7. %BattlefieldEntryField:SetMatchTipsHD
-- 8. %BattlefieldEntryField:_OnTeamCreated
-- 9. %evtBattlefieldEntryTeamMemberUpdated
-- 10. %s%s%d
-- 11. (AA
-- 12. (AC
-- 13. (BattlefieldEntryField:SetIsPlayingIntro
-- 14. (w@
-- 15. )AA
-- 16. )AB
-- 17. )AC
-- 18. )AE
-- 19. )AF
-- 20. )BA
-- 21. )BattlefieldEntryField:ResetToDefaultMaps
-- 22. )BattlefieldEntryField:_OnTeamInfoUpdated
-- 23. *BattlefieldEntryField:_OnTeamModesChanged
-- 24. *DFM.YxFramework.Managers.Module.FieldBase
-- 25. ,@
-- 26. 0BattlefieldEntryField:GetModeList empty maplist
-- 27. 0BattlefieldEntryField:_OnTDMMapBoardInfoUpdated
-- 28. 1BattlefieldEntryField:_OnPlayerArmedForceChanged
-- 29. 5BattlefieldEntryField:GetCatchedMatchIdListByGroupId
-- 30. 5BattlefieldEntryField:_OnMapChanged #mapInfo == 0!!!
-- 31. 6BattlefieldEntryField:SetCatchedMatchIdListAndGroupId
-- 32. 7BattlefieldEntryField:ResetToDefaultMaps no open group
-- 33. A@@
-- 34. A@D
-- 35. AddLuaEvent
-- 36. BDFM.Business.Module.BattlefieldEntryModule.BattlefieldEntryConfig
-- 37. BattlefieldEntry
-- 38. BattlefieldEntryField
-- 39. CBattlefieldEntryField:_OnTDMMapBoardInfoUpdated, in lobby gameflow
-- 40. ClearLoadoutInfo
-- 41. ClockManager
-- 42. Config
-- 43. ConfigManager
-- 44. Ctor
-- 45. EGameFlowStageType
-- 46. ELuaLogCategory
-- 47. EnumGroupID
-- 48. Events
-- 49. Facade
-- 50. FromHeroID2NameOffset

-- 重构的函数结构:

-- 可能的函数: 1BattlefieldEntryField:_OnPlayerArmedForceChanged
-- 可能的赋值: 5BattlefieldEntryField:_OnMapChanged #mapInfo == 0!!!
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: _OnPlayerArmedForceChanged
-- 可能的函数: armedForceInfoList
-- 可能的函数: evtTdmPlayerArmedForceChanged
-- 可能的函数: format
-- 可能的日志: logtable
-- 可能的日志: print