-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  &local=zh_TW&garena_channelid=0
-- 2.  = 
-- 3.  CallSceneCtrlFunctionBySubstage
-- 4.  DFM.YxFramework.Util.WidgetUtil
-- 5.  PlayCharacterAnimSeqByFashionId
-- 6.  extraParam: 
-- 7.  type: 
-- 8. !DFM.YxFramework.Plugin.Json.Json
-- 9. !GameletLogic.ShowReward itemID: 
-- 10. !GetBelongedHeroIdByHeroFashionId
-- 11. !SetDisplayWeaponAutoBoundAdapter
-- 12. " VersionUtil.IsGameChannelSteam()
-- 13. "GameletLogic.OnViewAboutToDestroy
-- 14. "GameletLogic.OnViewCreated layer:
-- 15. "GetOnlinePlayerStateFromStateCode
-- 16. #AsyncOperateStreamLevelsBySubStage
-- 17. #shareArkMessageToQQInSilenceResult
-- 18. #{"attr1":"","attr2":"","attr3":""}
-- 19. $pandoraShareArkMessageToQQInSilence
-- 20. %UpdateDetailViewPositionByWidgetInfo
-- 21. &GameletLogic.OnReportData: eventName:
-- 22. &GameletModule:Gamelet Error Nogamelet
-- 23. &app_item_id=
-- 24. &channelid=
-- 25. &gameid=
-- 26. &prefix=garena.df.dc.
-- 27. &roleId=
-- 28. &source=
-- 29. &ts=
-- 30. (@@
-- 31. (@A
-- 32. (AA
-- 33. (AB
-- 34. (AC
-- 35. (AE
-- 36. (BB
-- 37. (BH
-- 38. (CB
-- 39. (GameletLogic.OnViewCreated appID 
-- 40. (GameletLogic.OnViewCreated onLoadFinish
-- 41. (w@
-- 42. )@@
-- 43. )@A
-- 44. )@B
-- 45. )A@
-- 46. )AA
-- 47. )AB
-- 48. )AE
-- 49. )AF
-- 50. )BB

-- 重构的函数结构:

-- 可能的函数:  &local=zh_TW&garena_channelid=0
-- 可能的赋值:  = 
-- 可能的函数:  CallSceneCtrlFunctionBySubstage
-- 可能的赋值: &app_item_id=
-- 可能的赋值: &channelid=
-- 可能的赋值: &gameid=
-- 可能的赋值: &prefix=garena.df.dc.
-- 可能的赋值: &roleId=
-- 可能的赋值: &source=
-- 可能的赋值: &ts=
-- 可能的函数: ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- 可能的函数: .GameletLogic pandoraGetProductPayInfoReq item
-- 可能的函数: /GameletLogic pandoraGetProductPayInfoReq price
-- 可能的函数: 3GameletLogic pandoraGetProductPayInfoReq productID
-- 可能的函数: <GameletLogic pandoraGetProductPayInfoReq registrationRegion
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetGameInfoReq
-- 可能的函数: GetGameInfoRsp
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: GetWeaponSkinIfExists
-- 可能的函数: OnBaseResultNotifyEvent
-- 可能的函数: PLATFORM_ANDROID
-- 可能的函数: PLATFORM_IOS
-- 可能的函数: PLATFORM_OPENHARMONY
-- 可能的函数: getUserInfoResult
-- 可能的赋值: os=
-- 可能的函数: pandoraGetPayInfoReq
-- 可能的函数: pandoraGetPayInfoRes
-- 可能的函数: pandoraGetProductPayInfoReq'
-- 可能的函数: pandoraGetProductPayInfoRes
-- 可能的赋值: serverId=