-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1. "CommonVideoChangeView:OnNavBack()
-- 2. "WBP_CommonFullScreenVideo_Change2
-- 3. (AB
-- 4. (AC
-- 5. (w@
-- 6. )A@
-- 7. )B@
-- 8. )BB
-- 9. ,@@
-- 10. ,@A
-- 11. >DFM.Business.Module.CommonWidgetModule.Logic.CommonVideoLogic
-- 12. CCommonVideoChangeView:OnInitExtraData, Device not allowed CG play!
-- 13. CancelDelay
-- 14. CloseUI
-- 15. Collapsed
-- 16. CommonTips
-- 17. CommonVideoChangeView
-- 18. CommonWidget
-- 19. Config
-- 20. Ctor
-- 21. DFCommonMediaView
-- 22. DelayCall
-- 23. ELuaLogCategory
-- 24. EMediaDownloadType
-- 25. EUMGSequencePlayMode
-- 26. EnableCGMediaPlay
-- 27. Event
-- 28. Facade
-- 29. Field
-- 30. Forward
-- 31. GenLocalLogFunc
-- 32. GetVideoConfigData
-- 33. Loc
-- 34. LuaMCommonWidget
-- 35. LuaS
-- 36. Module
-- 37. NDFM.Business.Module.CommonWidgetModule.UI.CommonVideoView.CommonVideoViewBase
-- 38. OnClicked
-- 39. OnClose
-- 40. OnCloseBtnClicked
-- 41. OnHide
-- 42. OnInitExtraData
-- 43. OnNavBack
-- 44. OnOpen
-- 45. OnPlayEnd
-- 46. OnShow
-- 47. Play
-- 48. PlayAnimation
-- 49. QDFM.Business.Module.CommonWidgetModule.UI.CommonVideoView.CommonVideoProgressBar
-- 50. ShowSimpleTip

-- 重构的函数结构:

-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: format