-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  _resourceCommercializationTable
-- 2. !GetResourceCommercializationById
-- 3. !StoreField:GetCanMandelStopAudio
-- 4. !StoreField:SetCanMandelStopAudio
-- 5. "[Store] StoreField:GetSafeBoxInfo
-- 6. #InitResourceCommercializationTable
-- 7. $(%d+)-(%d+)-(%d+) (%d+):(%d+):(%d+)
-- 8. 'StoreField:SetLotteryData: Update data
-- 9. (A@
-- 10. (AA
-- 11. (C@
-- 12. (Resource/ResourceCommercializationTable
-- 13. (w@
-- 14. )A@
-- 15. )BC
-- 16. )CA
-- 17. )CB
-- 18. )CF
-- 19. )GetDictStoreLotteryProbDistributionItems
-- 20. *DFM.YxFramework.Managers.Module.FieldBase
-- 21. +[Store] StoreField:GetSafeBoxEnduranceInfo
-- 22. ,@
-- 23. ,@@
-- 24. 1[StoreField] GetStoreItemList allItemList is nil
-- 25. 4GetDictStoreLotteryProbDistributionItemsByLotteryID
-- 26. 9DFM.StandaloneLua.BusinessTool.StructTool.ItemConfigTool
-- 27. Alphabet
-- 28. ArmedForceData
-- 29. ArmedForceId
-- 30. AutoPlayVideoList
-- 31. CheckVideoNeedAutoPlay
-- 32. Config
-- 33. Cost
-- 34. Ctor
-- 35. Default
-- 36. ELuaLogCategory
-- 37. EStoreMainTab
-- 38. EStoreSortType
-- 39. EStoreSpecialSubTab
-- 40. Facade
-- 41. FilterStoreItemList
-- 42. GenLocalLogFunc
-- 43. GenTabInfo
-- 44. Get  _lotteryTabNum: 
-- 45. GetAllCost
-- 46. GetCanMandelStopAudio
-- 47. GetCanPlayMusic
-- 48. GetCollabTabVedioPlayed
-- 49. GetCurCost
-- 50. GetCurMandelMusicName

-- 重构的函数结构:

-- 可能的函数: ArmedForceData
-- 可能的函数: ArmedForceId
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetSortFunction
-- 可能的函数: declare_if_nil