-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  DFM.YxFramework.Util.WidgetUtil
-- 2. !CreateIVCommonItemTemplateBySize
-- 3. $WBP_SeasonalTasks_ContractDetail_in
-- 4. %s%s
-- 5. (AA
-- 6. (AB
-- 7. (BB
-- 8. (w@
-- 9. )A@
-- 10. )AA
-- 11. )AG
-- 12. )AJ
-- 13. +DFM.Business.Module.QuestModule.QuestLogic
-- 14. ,@@
-- 15. ,@A
-- 16. -QuestSeasonFactContractDetail:FreshBGImage()
-- 17. A@@
-- 18. A@C
-- 19. Accepted
-- 20. AddInputActionBinding
-- 21. AddListener
-- 22. AddLuaEvent
-- 23. AddNavWidgetToArray
-- 24. BindCustomBoundaryNavRule
-- 25. BindingNotBind
-- 26. C QuestSeasonFactContractDetail OnInitExtraData : questInfo is nil 
-- 27. CanAccept
-- 28. ClearSubUIByParent
-- 29. CloseAllPopUI
-- 30. Collapsed
-- 31. CommonBar
-- 32. CommonTips
-- 33. CommonWidget
-- 34. Completed
-- 35. Config
-- 36. Ctor
-- 37. DFCanvasPanel
-- 38. DFCommonButtonOnly
-- 39. DFSizeBox_0
-- 40. DoAcceptQuest
-- 41. DoFactAcceptQuest
-- 42. DoGetQuestRewards
-- 43. Down
-- 44. ECheckButtonState
-- 45. EDisplayInputActionPriority
-- 46. EIVWarehouseTempComponent
-- 47. EInputEvent
-- 48. EItemDetailFromUIType
-- 49. ELuaLogCategory
-- 50. ESlateVisibility

-- 重构的函数结构:

-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetSecondsFormatDDHHMMSS
-- 可能的函数: format