-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  ActivityTypeMPComponentDelivery
-- 2.  ActivityTypeRaidLotteryTemplate
-- 3.  ActivityTypeRecruitNewMilestone
-- 4.  DFM.YxFramework.Util.WidgetUtil
-- 5.  GetCommonBarRegInfoAndGroupInfo
-- 6.  RegStackUITopBarTabGroupRegInfo
-- 7.  _OnNotifyInputTypeChangedHandle
-- 8. !ActivityTypeSOLComponentDelivery
-- 9. !ActivityTypeSOLEquipmentDelivery
-- 10. !GetActivityGroupPresentationInfo
-- 11. !Mobile_SetSelectedGroupTabButton
-- 12. !RegStackUITopBarCurrencyTypeList
-- 13. !evtActivitySubBetweenInteractive
-- 14. !evtExchangeChangeBoxStateChanged
-- 15. "ActivityTypeTestingWeaponTemplate
-- 16. "CancelTrackedTaskTrackCurrenttask
-- 17. "RegisterStaticReddotDotWithConfig
-- 18. "[activitysub] OnHoverScrollBoxBtn
-- 19. "_OnProcessTrackRewardRromptWidget
-- 20. $[activitysub] OnUnhoverScrollBoxBtn
-- 21. %ActivityTypeAnythingExchangeCurrency
-- 22. &evtActivityRoleSurveyExchangeClickEnd
-- 23. 'ActivityUniversalExchangeTemplatePanel
-- 24. (@A
-- 25. (A@
-- 26. (AA
-- 27. (AC
-- 28. (AD
-- 29. (AE
-- 30. (AO
-- 31. (AT
-- 32. (BA
-- 33. (CA
-- 34. (DD
-- 35. (EA
-- 36. (SystemSettingMainView Customer Services
-- 37. (WBP_Activity_DailyActivity_TurnPage_out
-- 38. (_OnEventActivityRoleSurveyExchangeClick
-- 39. (w@
-- 40. )@@
-- 41. )A@
-- 42. )AA
-- 43. )AB
-- 44. )AC
-- 45. )AD
-- 46. )AE
-- 47. )AF
-- 48. )AG
-- 49. )AH
-- 50. )AI

-- 重构的函数结构:

-- 可能的函数:  _OnNotifyInputTypeChangedHandle
-- 可能的函数: *_ForceUpdateScrollBarVisibilityWorkaround
-- 可能的赋值: =DFM.Business.Module.ActivityModule.Logic.ActivityRedDotLogic
-- 可能的赋值: >ActivityMainPanel:OnPrevOrNextActivity  SubUI-CheckHotzone = 
-- 可能的函数: ArmedForceServer
-- 可能的赋值: BActivityMainPanel:OnPrevOrNextActivity  SubUI-HandlePrevOrNext = 
-- 可能的函数: CheckIfAutoApplyTheme
-- 可能的函数: Forward
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetCurArmedForceMode
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: GetMousePositionOnPlatform
-- 可能的函数: GoForward
-- 可能的函数: HasForecastDataOnly
-- 可能的函数: KeyForModeAndTab
-- 可能的函数: KeyForTab
-- 可能的函数: ListenInformation
-- 可能的函数: PlatformPaddingBox_1
-- 可能的函数: PlatformPaddingBox_2
-- 可能的函数: ShowErrorTipIfNeeded
-- 可能的函数: _GoForwardOrBackward
-- 可能的函数: _OnGoForward
-- 可能的函数: _wtActivityMainInfoRoot
-- 可能的函数: _wtPlatformRewardBox
-- 可能的赋值: aResource/Texture/Activity/C=AB3EA0A85B642B226A2C61D618BFE1AAAB8A425FF0C81332B84F86D8FB9EA13B.png
-- 可能的函数: evtNewGoForward
-- 可能的函数: format
-- 可能的函数: function