-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CallSceneCtrlFunctionBySubstage
-- 2.  GetMainFirstShowRewardIDByParam
-- 3.  PlayCharacterAnimSeqByFashionId
-- 4.  [BattlePassLogic] ShowRewardSub
-- 5. !GetBelongedHeroIdByHeroFashionId
-- 6. !GetMainFirstShowRewardPosByParam
-- 7. !GetMainRewardItemByPositionIndex
-- 8. #AsyncOperateStreamLevelsBySubStage
-- 9. $FoceCallSceneCtrlFunctionBySubstage
-- 10. '[BattlePassLogic] PayProcess param nil
-- 11. (@A
-- 12. (A@
-- 13. (AB
-- 14. (AF
-- 15. (B@
-- 16. (BE
-- 17. (CD
-- 18. (CF
-- 19. ([BattlePassLogic] ShowReward delay call
-- 20. (w@
-- 21. )@@
-- 22. )@A
-- 23. )@B
-- 24. )@C
-- 25. )A@
-- 26. )AA
-- 27. )AB
-- 28. )AC
-- 29. )B@
-- 30. )BB
-- 31. )CB
-- 32. )DD
-- 33. +_OnEventBattlePassRewardItemClick position
-- 34. ,[BattlePassLogic] ShowReward timeSpan < 0.5
-- 35. -SetSceneBackgroundAssetBySwitchTextureByPath
-- 36. .DFM.StandaloneLua.BusinessTool.HeroHelperTool
-- 37. .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- 38. .[BattlePassLogic] SetCamera display type same
-- 39. 0[BattlePassLogic] ShowRewardAfterCameraMoveDone
-- 40. 1DFM.Business.Module.StoreModule.Logic.StoreLogic
-- 41. 1DFM.StandaloneLua.BusinessTool.VehicleHelperTool
-- 42. 333333
-- 43. 3BattlePassLogic:ShowBattleProcess() no server data
-- 44. 5BattlePassLogic:ShowBattleProcess() calc pre iItemID
-- 45. 6[BattlePassLogic] ShowReward delay call reward id nil
-- 46. 9DFM.StandaloneLua.BusinessTool.StructTool.ItemConfigTool
-- 47. :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
-- 48. ;DFM.Business.Module.CollectionModule.Logic.CollectionLogic
-- 49. >DFM.Business.Module.VehicleModule.Logic.VehicleUIContextLogic
-- 50. ?DFM.Business.Module.LobbyDisplayModule.Logic.LobbyDisplayLogic

-- 重构的函数结构:

-- 可能的函数:  CallSceneCtrlFunctionBySubstage
-- 可能的函数: $FoceCallSceneCtrlFunctionBySubstage
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetLocalTimestamp
-- 可能的函数: GetNumberFormatStr
-- 可能的函数: GetWeaponSkinIfExists
-- 可能的函数: PictureTransforms
-- 可能的函数: format