-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  EInputAction_VehicleFireBtnDown
-- 2. "GetCurrentClientCharacterAvatarID
-- 3. #ABionicBirdActor::OnStopControl_ES
-- 4. $ABionicBirdActor::OnStartControl_ES
-- 5. %DFM.YxFramework.Managers.Timer.Timer
-- 6. &MetaDorianDriver:Init() RTTITypeNum: 
-- 7. &MetaDorianDriver:Init() StubFuncNum: 
-- 8. (@@
-- 9. (AA
-- 10. (AB
-- 11. (ABionicBirdActor::ProcessInputAction_BS
-- 12. (AC
-- 13. (B@
-- 14. (w@
-- 15. *@B
-- 16. *@C
-- 17. ,ZiplineActor_InitInCenterInteractor_BS Next
-- 18. -11.. MetaDorianDriver:Init() StubModuleNum: 
-- 19. -DFMAbility_ABionicBirdActor_OnStopControl_ES
-- 20. -UDFMWeaponTacticalEquipItem::OnBtnClicked_BS
-- 21. -ZiplineActor_InitInCenterInteractor_BS Enter
-- 22. .DFMAbility_ABionicBirdActor_OnStartControl_ES
-- 23. 0UWeaponAdapterItemRangeScope::OnWeaponEnable_BS
-- 24. 11... MetaDorianDriver:Init() 
-- 25. 2DFMAbility_ABionicBirdActor_ProcessInputAction_BS
-- 26. 2MetaDorianDriver.lua(Impl Version) Is Required...
-- 27. 333333
-- 28. 3UDFMAbilityPlayMontageSystem::BindUnEquipToTask_BS
-- 29. 3UDFMMobileWeaponTacticalEquipItem::OnBtnClicked_BS
-- 30. 3ZiplineActor_InitInCenterInteractor_BS Check World
-- 31. 4AInteractor_ZiplineActor::InitInCenterInteractor_BS
-- 32. 4UGPCharacterMovementComponent::OnEndCustomIdling_BS
-- 33. 6UGPCharacterMovementComponent::OnBeginCustomIdling_BS
-- 34. 7DFMGameHud_UDFMWeaponTacticalEquipItem_OnBtnClicked_BS
-- 35. 7UMapBaseHUDController::OnClientMarkDetectorLocation_BS
-- 36. :GPGameplay_UWeaponAdapterItemRangeScope_OnWeaponEnable_BS
-- 37. =DFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS
-- 38. =DFMGameHud_UDFMMobileWeaponTacticalEquipItem_OnBtnClicked_BS
-- 39. >DFMGameHud_UDFMWeaponTacticalEquipItem_OnBtnClicked_BS Hotfix
-- 40. >GPGameplay_UGPCharacterMovementComponent_OnEndCustomIdling_BS
-- 41. >ZiplineActor_InitInCenterInteractor_BS ActorWrold Null return
-- 42. ?DFMGameplay_AInteractor_ZiplineActor_InitInCenterInteractor_BS
-- 43. @DFMGameHud_UDFMWeaponTacticalEquipItem_OnBtnClicked_BS Hotfix 1
-- 44. @DFMGameHud_UDFMWeaponTacticalEquipItem_OnBtnClicked_BS Hotfix 2
-- 45. @DFMGameHud_UDFMWeaponTacticalEquipItem_OnBtnClicked_BS Hotfix 3
-- 46. @GPGameplay_UGPCharacterMovementComponent_OnBeginCustomIdling_BS
-- 47. AActor
-- 48. ADFMCharacter
-- 49. ADFMGameHud_UMapBaseHUDController_OnClientMarkDetectorLocation_BS
-- 50. AddDorianFunction

-- 重构的函数结构:

-- 可能的赋值: =DFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS
-- 可能的赋值: =DFMGameHud_UDFMMobileWeaponTacticalEquipItem_OnBtnClicked_BS
-- 可能的函数: AddDorianFunction
-- 可能的函数: GetLocalPlayerCamp
-- 可能的赋值: HDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS AnimIns = 
-- 可能的赋值: HDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS FPPMesh = 
-- 可能的函数: MUDFInteractableCompProxy_FortificationProxy::IsCanInteract_Implementation_BS
-- 可能的函数: MUDFInteractableCompProxy_FortificationProxy::IsShowableTag_Implementation_BS
-- 可能的赋值: PDFMAbility_UDFMAbilityPlayMontageSystem_BindUnEquipToTask_BS ActivateAnimIns = 
-- 可能的函数: PLATFORM_ANDROID
-- 可能的函数: PLATFORM_IOS
-- 可能的函数: TryStopLockLocalCharacter
-- 可能的函数: YBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS
-- 可能的函数: YBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS
-- 可能的函数: iBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS World isinvalid
-- 可能的函数: iBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS World isinvalid
-- 可能的函数: kBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS SelfPtr isinvalid
-- 可能的函数: kBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS SelfPtr isinvalid
-- 可能的日志: logerror
-- 可能的日志: print
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS FreeBuildOwnerCamp==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS SelfPtr.RecycleTag==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS FreeBuildOwnerCamp==nil
-- 可能的函数: qBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS SelfPtr.RecycleTag==nil
-- 可能的函数: vBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS FortificationProxy isinvalid
-- 可能的函数: vBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS FortificationProxy isinvalid
-- 可能的函数: wBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS LocalCamp~=0 and LocalCamp~=1
-- 可能的函数: wBreakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS LocalCamp~=0 and LocalCamp~=1
-- 可能的函数: |Breakthrough_UDFInteractableCompProxy_FortificationProxy_IsCanInteract_Implementation_BS type(FreeBuildOwnerCamp) ~= number
-- 可能的函数: |Breakthrough_UDFInteractableCompProxy_FortificationProxy_IsShowableTag_Implementation_BS type(FreeBuildOwnerCamp) ~= number