-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  CallSceneCtrlFunctionBySubstage
-- 2.  DFM.YxFramework.Util.WidgetUtil
-- 3.  PlayCharacterAnimSeqByFashionId
-- 4.  SetCameraFadeIfCurDisableRender
-- 5.  get unLockInfo is nil
-- 6. !DisableDynamicNavConfigsbyWidget
-- 7. !HallExpertLevelSequenceComponent
-- 8. !RegStackUITopBarCurrencyTypeList
-- 9. !SetBottomBarTempInputSummaryList
-- 10. !heroId is empty, get data failed
-- 11. #HeroMainPanel:_OnOpenHeroProfile()
-- 12. %HeroMainPanel:OnHide fix model reset
-- 13. %Mini button id is empty, jump failed
-- 14. &NewUnlockCommerceItem_Customization%s
-- 15. (AA
-- 16. (AB
-- 17. (AC
-- 18. (AE
-- 19. (CE
-- 20. (CF
-- 21. ([echewzhu]HeroMainPanel:uins is invalid
-- 22. (w@
-- 23. )@@
-- 24. )@A
-- 25. )A@
-- 26. )AA
-- 27. )AB
-- 28. )AC
-- 29. )AD
-- 30. )AE
-- 31. )AL
-- 32. )AP
-- 33. )AT
-- 34. )B@
-- 35. )BA
-- 36. )BB
-- 37. )BC
-- 38. )BF
-- 39. )CE
-- 40. )CG
-- 41. )CH
-- 42. )Jump pass failed, JumpId judged as empty
-- 43. *@@
-- 44. *DFM.Business.Module.HeroModule.HeroConfig
-- 45. *Failed to obtain the first button control
-- 46. +Failed to obtain the second button control
-- 47. , jump id is 
-- 48. ,@@
-- 49. ,@E
-- 50. ,@G

-- 重构的函数结构:

-- 可能的函数:  CallSceneCtrlFunctionBySubstage
-- 可能的函数:  SetCameraFadeIfCurDisableRender
-- 可能的函数: 4BtnData data is empty, jump function setting failed
-- 可能的函数: 5Failed to execute function jump, type judgment error
-- 可能的函数: ?HeroMainPanel: hero get gift data by hero's gift id. hero id =
-- 可能的函数: ArmedForceData
-- 可能的函数: ArmedForceID
-- 可能的函数: ArmedForceId
-- 可能的函数: ArmedForceServer
-- 可能的函数: EArmedForceMode
-- 可能的函数: Forward
-- 可能的赋值: G[echewzhu]HeroMainPanel:_SetExpertSceneAttrs : heroFashionSuitIdStr = 
-- 可能的函数: GenLocalLogFunc
-- 可能的函数: GetCurArmedForceMode
-- 可能的函数: GetHeroArmedForceId
-- 可能的函数: GetMallGiftDataByGoodsID
-- 可能的函数: GetNumberFormatStr
-- 可能的函数: Key2StrFormat
-- 可能的函数: SetSceneEffectColorOverLife
-- 可能的函数: _armedForceId2HeroItemUIInst
-- 可能的函数: evtSelectHeroIdForShowChanged
-- 可能的函数: format
-- 可能的函数: gift data =
-- 可能的函数: gift id =