-- Lua源代码还原 (伪代码)
-- 从字节码中提取的信息

-- 提取的字符串:
-- 1.  SafeAndCardPackActivatingConfig
-- 2.  itemMainType itemSubType : 
-- 3. !WeaponSkin/MysticalSkinBasicPara
-- 4. "GetPendantMysticalDetailInfoTable
-- 5. $WeaponSkin/PendantMysticalSkinTable
-- 6. %WeaponSkin/MysticalSkinInfoDataTable
-- 7. %s-%d
-- 8. &WeaponMelee/WeaponMeleeAttributeTable
-- 9. (AA
-- 10. (BB
-- 11. (w@
-- 12. )@@
-- 13. )A@
-- 14. )AB
-- 15. )Linear color for quality [%d] not found.
-- 16. *WeaponSkin/MysticalPendantDetailInfoTable
-- 17. +Buff ID [%d] not configured, please check!
-- 18. +Buff ID [%s] not configured, please check!
-- 19. +config is nil, plz check CommercializeData
-- 20. -Buff Type [%s] not configured, please check!
-- 21. .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- 22. /Bag Func ID [%d] not configured, please check!
-- 23. 3000
-- 24. 3SafeBox Func ID [%d] not configured, please check!
-- 25. 4ItemConfigTool.GetMeleeAttributeTable nil, item id:
-- 26. 5ItemConfigTool.GetItemArmedForceCfgNew nil, item id:
-- 27. 8ChestHanging Func ID [%d] not configured, please check!
-- 28. A00
-- 29. ActiveTime
-- 30. ArmedForceProps
-- 31. Armor/BodyArmorFunction
-- 32. Armor/HelmetArmorFunction
-- 33. BagFunc
-- 34. BattlePassServer
-- 35. Blue
-- 36. BuffClientPerformance
-- 37. BuffEffect
-- 38. BuffType
-- 39. CheckIsInFrontEnd
-- 40. CheckItemHasConfig
-- 41. ChestHangingFunc
-- 42. ClockManager
-- 43. CloseModuleType
-- 44. Collapsed
-- 45. ColorManager
-- 46. CommercializeData
-- 47. CommercializeImage
-- 48. CommercializeType
-- 49. CommonItemAsset
-- 50. DeafultTag

-- 重构的函数结构:

-- 可能的函数: )Linear color for quality [%d] not found.
-- 可能的函数: 5ItemConfigTool.GetItemArmedForceCfgNew nil, item id:
-- 可能的函数: ArmedForceProps
-- 可能的函数: Armor/BodyArmorFunction
-- 可能的函数: Armor/HelmetArmorFunction
-- 可能的函数: BuffClientPerformance
-- 可能的函数: GetBodyArmorFunctionById
-- 可能的函数: GetBuffPerformanceByType
-- 可能的函数: GetBuffPerformanceByTypeEnum
-- 可能的函数: GetHelmetArmorFunctionById
-- 可能的函数: GetItemArmedForceCfgNew
-- 可能的函数: format
-- 可能的日志: logbox
-- 可能的日志: logerror
-- 可能的日志: loginfo
-- 可能的日志: logwarning