-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:19:59.345742

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMSystemSettingimportClient
-- @DFM.Business.Module.LitePackageModule.Logic.LiteDownloadManager
-- ADFM.Business.Module.SystemSettingModule.Logic.VolumeSettingLogic
-- BDFM.Business.Module.SystemSettingModule.Logic.DisplaySettingLogic
-- import
-- require

-- 常量定义
-- local AutoOptimize
-- local AutoPowerOpt
-- local Balance
-- local BindBtnEvent
-- local BindMouseEndCallBack
-- local BloomQuality
-- local Button
-- local Button_231
-- local ClientDisplaySetting
-- local ClientVolumeSetting
-- local Collapsed
-- local Color1
-- local Color2
-- local Color3
-- local Color4
-- local ColorAndOpacity
-- local ColorFul
-- local ColorHitEffect
-- local Colorful
-- local CommonTips
-- local Config
-- local ConvertColor
-- local CopyrightMusicPlayback
-- local Ctor
-- local DFCheckBox_26
-- local DFImage_257
-- local DFImage_49
-- local DFMGamePlayerMode
-- local DFMSystemSettingHelper
-- local DOF

-- 函数实现
