-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:01.406921

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMLitePackagerequire%DFM.YxFramework.Core.Class.CppObjectLiteDownloadManagerclass
CppObjectimportLitePackageWrapperGetInstanceGetGameInstanceGameSDKManagerGetFlibPakHelper=DFM.Business.Module.LitePackageModule.Logic.LitePackageLogic>DFM.Business.Module.LitePackageM
-- !DFM.YxFramework.Plugin.Json.Json
-- %DFM.YxFramework.Core.Class.CppObject
-- 1DFM.StandaloneLua.BusinessTool.VehicleHelperTool
-- ;DFM.StandaloneLua.BusinessTool.LogAnalysis.LogAnalysisTool
-- =DFM.Business.Module.LitePackageModule.Logic.LitePackageLogic
-- >DFM.Business.Module.LitePackageModule.Logic.LiteDownloadQuest
-- GDFM.Business.DataStruct.LitePackageStruct.LitePackageDownloadTableItem
-- import
-- require

-- 常量定义
-- local AAD
-- local ABA
-- local ABB
-- local ADH
-- local AEF
-- local Adapter
-- local Add
-- local AddGameEvent
-- local AddLuaEvent
-- local AddNetWorkControlEvent
-- local AnimShow
-- local AsyncRequestPermissions
-- local Auto
-- local AutoBeginDownloadHD
-- local AutoDownloadTrigger
-- local Bag
-- local BattlePass
-- local BeforeLogin
-- local BeforeLoginHD
-- local BreastPlate
-- local CachModuleToDownload
-- local CachQuestToDownload
-- local CalcFileMD5
-- local CalcLastVersionPakInfos
-- local CancelAll
-- local CancelByModuleName
-- local CancelByQuestID
-- local CancelDownloadHDCollection
-- local Card
-- local Category

-- 函数实现
