-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.308347

-- 模块导入
--  DFM.YxFramework.Util.WidgetUtil
-- -DFM.YxFramework.Managers.UI.Util.UIThemeUtil
-- 4DFM.YxFramework.Managers.Resource.Util.ResImageUtil
-- :DFM.Business.Module.CommonWidgetModule.UI.HD.HDKeyIconBox
-- import
-- require

-- 常量定义
-- local AnyKeyIconVisible
-- local AsyncLoadImgObjByPath
-- local AsyncSetImageIconPathAllState
-- local AsyncSetImagePath
-- local BP_SetMainTitle
-- local BP_ShowHoldProgressBarTips
-- local BP_UpdateProgressBar
-- local ButtonClick
-- local ButtonInternal
-- local ButtonState
-- local CheckIfAutoApplyTheme
-- local Collapsed
-- local Ctor
-- local DFCommonButton
-- local DFCommonButtonOnly
-- local DFCommonButton_PCOnly
-- local DFHD_LUA
-- local DFScaleBox_0
-- local Deactivated
-- local Disabled
-- local EButtonState
-- local EButtonTouchMethod
-- local ELuaLogCategory
-- local Event
-- local GenLocalLogFunc
-- local GetActivatedState
-- local GetIsEnabled
-- local GetKeyIconWidget
-- local GetObjectClassName
-- local HandleClicked

-- 函数实现
