-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:19:59.386676

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMSystemSettingimportGPGConfigUti
-- !DFM.YxFramework.Plugin.Json.Json
-- @DFM.Business.Module.SystemSettingModule.Logic.HD.SettingLogicHD
-- CDFM.Business.Module.SystemSettingModule.Logic.HD.SettingRegLogicHD
-- FDFM.Business.Module.SystemSettingModule.Logic.HD.CommonSettingLogicHD
-- GDFM.Business.Module.SystemSettingModule.Logic.HD.UpgradeSettingLogicHD
-- HDFM.Business.Module.SystemSettingModule.Logic.HD.Debug.DummyServerLogic
-- import
-- require

-- 常量定义
-- local ADSList
-- local ADSListGamepad
-- local AccountServer
-- local AppliedIndex
-- local ApplyIndex
-- local ApplyKeySettingJsonStr
-- local AsyncShowUI
-- local AutoNamePrefix
-- local CSSettingGetValuesByTypeReq
-- local CSSettingPutKeyValueReq
-- local Case
-- local CheckAndSendSetting
-- local CheckPlayerNameValid
-- local CheckUnsave
-- local ClockManager
-- local CloudSettingIndex
-- local CloudSettingLocalCommon
-- local CloudSettingLocalKeymapping
-- local CloudSettingLocalTimeStamp
-- local CloudSettingTxt
-- local CommonSettingHD
-- local CommonTips
-- local Config
-- local CreateNameWindow
-- local Data
-- local DataKeySetting
-- local DebugOn
-- local DelayCall
-- local DeleteIndex
-- local EJet

-- 函数实现
