-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.028218

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaMCommonWidgetrequire DFM
--  DFM.YxFramework.Util.MemoryUtil
--  DFM.YxFramework.Util.WidgetUtil
-- >DFM.Business.Module.CommonWidgetModule.Logic.CommonVideoLogic
-- NDFM.Business.Module.CommonWidgetModule.UI.CommonVideoView.CommonVideoViewBase
-- QDFM.Business.Module.CommonWidgetModule.UI.CommonVideoView.CommonVideoProgressBar
-- import
-- require

-- 常量定义
-- local Add
-- local AddAxisInputActionBinding
-- local AddCloseOrRecycleCallback
-- local AddGPInputTypeChangedEvent
-- local AddInputActionBinding
-- local AddListener
-- local AddLuaEvent
-- local AddMouseButtonDownEvent
-- local AddPlayEndCallback
-- local AnyKey
-- local AnyKey_Axis
-- local BP_UpdateProgressBar
-- local BindAnyKeyPress
-- local BindSkipBtnClick
-- local BindSkipBtnPress
-- local BindSkipBtnRelease
-- local CancelDelay
-- local CheckMeidaFileExist
-- local CheckPufferFileUsable
-- local CheckSkipBtn
-- local Clear
-- local ClearMemory
-- local ClearUpdateBtnProgressTimer
-- local CloseUI
-- local Collapsed
-- local CommonTips
-- local CommonVideoFullScreenView
-- local CommonWidget
-- local Config
-- local CreateCPlusCallBack

-- 函数实现
