-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.334292

-- 常量定义
-- local BlackSite
-- local BlackSiteLevelFormat
-- local BlackSiteProduceFormulaItem
-- local BlackSiteUnlock
-- local CancelAllFrameTasks
-- local ClearSubUIByParent
-- local Collapsed
-- local Config
-- local Ctor
-- local ELuaLogCategory
-- local Facade
-- local GenLocalLogFunc
-- local InitExtraDataBySelf
-- local Loc
-- local LuaFramingManager
-- local LuaMBlackSite
-- local LuaS
-- local Module
-- local OnClose
-- local OnOpen
-- local RegisterFrameTask
-- local SetText
-- local UIManager
-- local UIName2ID
-- local UITextBlock
-- local UIWidgetBase
-- local Visible
-- local Wnd

-- 函数实现
