-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:19:59.149956

-- 模块导入
-- GenLocalLogFuncELuaLogCategoryLuaSSettlementclassSettlementServerrequire+DFM.YxFramework.Managers.Server.ServerBase!DFM.YxFramework.Plugin.Json.JsoncreateJsonimpor
-- !DFM.YxFramework.Plugin.Json.Json
-- +DFM.YxFramework.Managers.Server.ServerBase
-- .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- :DFM.Business.DataStruct.SettlementStruct.SettlementDefine
-- ADFM.YxFramework.Managers.GameFlow.InGameControl.InGameController
-- import
-- require

-- 常量定义
-- local AAA
-- local AAC
-- local ADL
-- local AED
-- local AccidentalDeath
-- local AccountServer
-- local Add
-- local AddLuaEvent
-- local AddNtfListener
-- local Arena
-- local AssistNo
-- local BindCutSceneEvent
-- local BindingTeammate
-- local Boss
-- local BreakthroughGPSubsystem
-- local BreastPlate
-- local BroadcastServerPlayerBan
-- local CSAchieveProgressUpdatedNtf
-- local CSGatewayKickPlayerNtf
-- local CSGetArenaSettlementInfoReq
-- local CSGetRaidSettlementInfoReq
-- local CSGetTDMSettlementInfoReq
-- local CSPlayerCommanderModePraiseReq
-- local CSPlayerInfoBePraisedNtf
-- local CSPlayerInfoPraiseReq
-- local CSSettlementEmptyNtf
-- local CarryOutPropsPos
-- local CheckIsFriend
-- local CheckIsGuide
-- local CheckIsNewMPSettlement

-- 函数实现
