-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:19:59.516470

-- 模块导入
--  DFM.YxFramework.Util.WidgetUtil
-- 3DFM.Business.Module.RewardModule.UI.RewardBaseView
-- 7DFM.Business.Module.RewardModule.Logic.RewardViewLogic
-- import
-- require

-- 常量定义
-- local Add
-- local AddInputActionBinding
-- local AddListeners
-- local AddLuaEvent
-- local AddSubUI
-- local AddSummaries
-- local BindCloseCallback
-- local CancelAnim
-- local CheckIsMoneyPaper
-- local ClearBatchInfo
-- local ClearSubUIByParent
-- local Collapsed
-- local Config
-- local CreateCPlusCallBack
-- local Ctor
-- local DFHorizontalBox_43
-- local DFVerticalBox_147
-- local DoSendOpenUILog
-- local EDisplayInputActionPriority
-- local EGPInputModeType
-- local EGPInputType
-- local EInputEvent
-- local EItemDetailFromUIType
-- local ELuaLogCategory
-- local ENavConfigPriority
-- local EUINavDynamicType
-- local EUMGSequencePlayMode
-- local EnableDynamicNavConfig
-- local Events
-- local Facade

-- 函数实现
