-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.395193

-- 模块导入
-- <DFM.Business.Module.IrisSafeHouseModule.IrisSafeHouseConfig
-- @DFM.Business.Module.LitePackageModule.Logic.LiteDownloadManager
-- GDFM.Business.Module.BattlefieldEntryModule.Logic.BattlefieldEntryLogic
-- require

-- 常量定义
-- local AccountPunishReason
-- local AccountServer
-- local AddListener
-- local ArmedForceServer
-- local BattlefieldEntry
-- local CancelMatch
-- local CantChangeMapWhenMatching
-- local CantMatchScoreReadyTipText
-- local Captain
-- local CaptainStartMatch
-- local CheckCanStartMatch
-- local CheckHasValidHero
-- local CheckIsCommanderMode
-- local CheckIsCommanderUnlock
-- local CheckIsMapEnough
-- local CheckIsModeLockedByPlayerLevel
-- local CheckIsModeLockedByRankScore
-- local CheckIsNeedDownloadAllMap
-- local CheckIsSupportTournament
-- local CheckMapIsDownload
-- local CheckRankLockedBySeasonLevel
-- local CheckTeammateIsReady
-- local CheckWIFIDownloadQuests
-- local CommonTips
-- local Config
-- local DFHD_LUA
-- local DFMAudioRes
-- local Download
-- local EArmedForceMode
-- local ELuaLogCategory

-- 函数实现
