-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:02.872067

-- 模块导入
-- /DFM.StandaloneLua.BusinessTool.SkillHelperTool
-- require

-- 常量定义
-- local AsyncSetImagePath
-- local BattleHeroSkillIcon
-- local Button_112
-- local Ctor
-- local DFHD_LUA
-- local DFTextBlock
-- local DFTextBlock_49
-- local DelayCall
-- local ELuaLogCategory
-- local Event
-- local GenLocalLogFunc
-- local GetSkillIconById
-- local Image_Talent
-- local LuaMHero
-- local LuaS
-- local OnClicked
-- local OnClose
-- local OnHovered
-- local OnOpen
-- local OnUnhovered
-- local SetColorAndOpacity
-- local SetCppValue
-- local SetExtraData
-- local SetIconColor
-- local SetSkillText
-- local SetText
-- local SetTextColor
-- local Timer
-- local UIButton
-- local UIImage

-- 函数实现
