-- Lua源代码重构
-- 基于字节码分析重构的代码结构

-- 导入模块
-- import "DFM.YxFramework.Util.AnalysisUtil
-- import %DFM.YxFramework.Managers.ManagerBase
-- import (DFM.YxFramework.Managers.UI.Util.UIUtil
-- import *DFM.YxFramework.Managers.UI.LuaUIBaseView
-- import *DFM.YxFramework.Managers.UI.UIGlobalConst
-- import ,DFM.StandaloneLua.BusinessTool.LocalizeTool
-- import /DFM.YxFramework.Managers.Resource.Stub.ResStub
-- import /DFM.YxFramework.Managers.UI.Input.InputMonitor
-- import /DFM.YxFramework.Managers.UI.Util.UIReleaseUtil
-- import 1DFM.YxFramework.Managers.UI.Handle.BatchUIHandle
