-- Lua源代码重构
-- 基于字节码分析重构的代码结构

-- 导入模块
-- import DFM.YxFramework.Util.WidgetUtil
-- import )DFM.Business.DataStruct.Common.Base.Safe
-- import *DFM.Business.DataStruct.Common.Base.Table
-- import -DFM.YxFramework.Managers.UI.Util.UIThemeUtil
-- import /DFM.Business.DataStruct.Common.Base.CallFilter
-- import 2DFM.Business.Module.ActivityModule.ActivityConfig
-- import 7DFM.Business.DataStruct.Common.Agent.InputBindingAgent
-- import 8DFM.Business.DataStruct.UIDataStruct.TabUIContentDataV2
-- import :DFM.Business.Module.CommonWidgetModule.CommonWidgetConfig
