-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:19:59.471624

-- 模块导入
-- GenLocalLogFuncELuaLogCategory
LuaMStorerequire9DFM.StandaloneLua.Busin
-- *DFM.YxFramework.Managers.Module.FieldBase
-- 9DFM.StandaloneLua.BusinessTool.StructTool.ItemConfigTool
-- require

-- 常量定义
-- local Alphabet
-- local ArmedForceData
-- local ArmedForceId
-- local AutoPlayVideoList
-- local CheckVideoNeedAutoPlay
-- local Config
-- local Cost
-- local Ctor
-- local Default
-- local ELuaLogCategory
-- local EStoreMainTab
-- local EStoreSortType
-- local EStoreSpecialSubTab
-- local Facade
-- local FilterStoreItemList
-- local GenLocalLogFunc
-- local GenTabInfo
-- local GetAllCost
-- local GetCanMandelStopAudio
-- local GetCanPlayMusic
-- local GetCollabTabVedioPlayed
-- local GetCurCost
-- local GetCurMandelMusicName
-- local GetCurMusicName
-- local GetCurrentTime
-- local GetDrawByType
-- local GetHeroTypeInfo
-- local GetIsOpeningBox
-- local GetIsStoreVar
-- local GetIsToPricePool

-- 函数实现
