-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.317260

-- 模块导入
-- .DFM.StandaloneLua.BusinessTool.ItemHelperTool
-- ;DFM.Business.Module.CollectionModule.Logic.CollectionLogic
-- ;DFM.StandaloneLua.BusinessTool.LogAnalysis.LogAnalysisTool
-- import
-- require

-- 常量定义
-- local AccountServer
-- local Add
-- local AddCollectionTabEntryTime
-- local AddListeners
-- local AddLuaEvent
-- local BattlefieldEntry
-- local BindBackHandler
-- local BindSetBackgourndCallback
-- local CDNIcon
-- local CanvasPanel_SubView
-- local CheckTopTabGroup
-- local ClearAllGunSkinFilterData
-- local ClearAllHangingFilterData
-- local ClearAllMysticalSkinFilterData
-- local ClearMysticalSkinInstanceList
-- local ClearSubUIByParent
-- local CloseAllPopUI
-- local CloseMainPanelProcess
-- local ClosePopup
-- local CloseUI
-- local Collapsed
-- local Collection
-- local CollectionMainPanel
-- local CollectionServer
-- local CollectionTabId2Info
-- local CommonBar
-- local Config
-- local ConfigManager
-- local CreateCPlusCallBack
-- local CreateCallBack

-- 函数实现
