-- Lua源代码解码结果
-- 基于字节码深度分析生成
-- 生成时间: 2025-10-23 04:20:03.412270

-- 模块导入
-- *DFM.YxFramework.Managers.Module.FieldBase
-- BDFM.Business.Module.BattlefieldEntryModule.BattlefieldEntryConfig
-- require

-- 常量定义
-- local AddLuaEvent
-- local BattlefieldEntry
-- local BattlefieldEntryField
-- local ClearLoadoutInfo
-- local ClockManager
-- local Config
-- local ConfigManager
-- local Ctor
-- local EGameFlowStageType
-- local ELuaLogCategory
-- local EnumGroupID
-- local Events
-- local Facade
-- local FromHeroID2NameOffset
-- local GameFlowManager
-- local GameModeServer
-- local GenLocalLogFunc
-- local GetAvailableTDMGroup
-- local GetCatchedMatchIdListByGroupId
-- local GetCurrentGameFlow
-- local GetGroupId
-- local GetGroupType
-- local GetHasResetMap
-- local GetIsModeOpen
-- local GetIsPlayingIntro
-- local GetLoadoutInfo
-- local GetLoadoutInfoArray
-- local GetLocalTimestamp
-- local GetMap
-- local GetMapList

-- 函数实现
